(()=>{
'use strict';
const OWNER_KEY='bp_owner_access_token';
const now=()=>Math.floor(Date.now()/1000);
function payload(token){try{const p=String(token||'').split('.')[1];if(!p)return null;const s=p.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(p.length/4)*4,'=');return JSON.parse(atob(s))}catch(_){return null}}
function usable(token){const p=payload(token);return !!(token&&p&&Number(p.exp||0)>now()+30)}
function extract(v){const out=[];const add=t=>{if(typeof t==='string'&&t.split('.').length===3)out.push(t)};try{if(typeof v==='string'){add(v);try{v=JSON.parse(v)}catch(_){return out}}if(Array.isArray(v)){for(const x of v)out.push(...extract(x));return out}if(v&&typeof v==='object'){add(v.access_token);add(v.currentSession?.access_token);add(v.session?.access_token);add(v.data?.session?.access_token);add(v.data?.access_token)}}catch(_){}return out}
function candidates(){const found=[];try{for(const store of [sessionStorage,localStorage]){for(let i=0;i<store.length;i++){const k=store.key(i)||'';if(k===OWNER_KEY||k.startsWith('sb-')&&k.endsWith('-auth-token')){for(const t of extract(store.getItem(k)||'')){const p=payload(t);found.push({token:t,exp:Number(p?.exp||0)})}}}}}catch(_){}return found.sort((a,b)=>b.exp-a.exp)}
function findValidToken(){const direct=sessionStorage.getItem(OWNER_KEY)||'';if(usable(direct))return direct;if(direct)sessionStorage.removeItem(OWNER_KEY);const c=candidates().find(x=>usable(x.token));if(c){sessionStorage.setItem(OWNER_KEY,c.token);return c.token}return''}
function prepare(){const t=findValidToken();if(!t)sessionStorage.removeItem(OWNER_KEY);return t}
function installOwnerShortcuts(){const add=()=>{if(!prepare())return;const links=document.querySelector('.toplinks');if(links&&!links.querySelector('[data-owner-investor-link]')){const a=document.createElement('a');a.className='btn';a.href='/owner/investor/';a.dataset.ownerInvestorLink='1';a.textContent='Investor + Export';links.insertBefore(a,links.querySelector('#refresh')||null);const p=document.createElement('a');p.className='btn';p.href='/owner/print/';p.dataset.ownerPrintLink='1';p.textContent='5 PDFs';links.insertBefore(p,links.querySelector('#refresh')||null)}const launch=document.querySelector('.launchgrid');if(launch&&!launch.querySelector('[data-owner-investor-launch]')){const a=document.createElement('a');a.className='launch';a.href='/owner/investor/';a.dataset.ownerInvestorLaunch='1';a.innerHTML='<b>Investor + Export</b><span>Valuation, workers, headless app watch, release gates, local node and global readiness</span>';launch.prepend(a);const p=document.createElement('a');p.className='launch';p.href='/owner/print/';p.dataset.ownerPrintLaunch='1';p.innerHTML='<b>Owner Print Pack</b><span>Five current PDF runbooks ready to open and print</span>';launch.prepend(p)}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(add,100),{once:true});else setTimeout(add,100)}
window.BP_OWNER_SESSION_V624={payload,usable,findValidToken,prepare};
prepare();installOwnerShortcuts();
})();
