# BridgePoint Local Agent - signed channel live-artifact
$ErrorActionPreference='Stop'
$AgentVersion=936
$Root=Join-Path $env:LOCALAPPDATA 'BridgePoint\LocalAI'
$ConfigPath=Join-Path $Root 'config.json'
$BackupConfigPath=Join-Path $Root 'backup-config.json'
$AgentPath=Join-Path $Root 'bridgepoint_local_ai.ps1'
$BackupToolDir=Join-Path $Root 'backup-tools'
$LogDir=Join-Path $Root 'logs'
$AgentUrl='https://raw.githubusercontent.com/olekingkole28-dot/bridgepoint-live/live-artifact/downloads/local-ai/bridgepoint_local_ai.ps1'
$BackupBaseUrl='https://raw.githubusercontent.com/olekingkole28-dot/bridgepoint-live/live-artifact/downloads/backup'
New-Item -ItemType Directory -Force -Path $LogDir,$BackupToolDir|Out-Null
$LogPath=Join-Path $LogDir ('agent-'+(Get-Date -Format 'yyyyMMdd')+'.log')
function Log([string]$m){$x=('{0:o} {1}' -f (Get-Date),$m);Add-Content $LogPath $x;Write-Host $x}
function Unprotect([string]$p){if([string]::IsNullOrWhiteSpace($p)){return ''};$s=ConvertTo-SecureString $p;$b=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($s);try{[Runtime.InteropServices.Marshal]::PtrToStringBSTR($b)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($b)}}
function LoadCfg{if(-not(Test-Path $ConfigPath)){throw 'BridgePoint Local AI is not enrolled.'};Get-Content $ConfigPath -Raw|ConvertFrom-Json}
function BP($cfg,[string]$token,[string]$action,$payload=@{}){$body=@{}+$payload;$body.action=$action;$body.node_id=[string]$cfg.node_id;Invoke-RestMethod -Method Post -Uri ([string]$cfg.endpoint) -Headers @{'x-bridgepoint-node-token'=$token} -ContentType 'application/json' -Body ($body|ConvertTo-Json -Depth 40 -Compress) -TimeoutSec 90}
function Has([string]$n){[bool](Get-Command $n -ErrorAction SilentlyContinue)}
function BackupRuntime{
 $r=[ordered]@{backup_authority=$false;restore_test_authority=$false;portable_export_authority=$false;destination='';config=$null}
 if(-not(Test-Path $BackupConfigPath)){return $r}
 try{$c=Get-Content $BackupConfigPath -Raw|ConvertFrom-Json;$r.config=$c;$r.destination=[string]$c.destination
  $deps=@('supabase','pg_dump','pg_restore','rclone','git');$missing=@($deps|Where-Object{-not(Has $_)})
  if([bool]$c.backup_enabled -and $missing.Count -eq 0){$d=Unprotect([string]$c.db_url_protected);$a=Unprotect([string]$c.s3_access_key_protected);$s=Unprotect([string]$c.s3_secret_key_protected);$r.backup_authority=($d -match '^postgres(ql)?://' -and $a -and $s);$d=$null;$a=$null;$s=$null}
  if([bool]$c.backup_enabled -and (Has 'psql')){$x=Unprotect([string]$c.db_url_protected);$r.portable_export_authority=($x -match '^postgres(ql)?://');$x=$null}
  if($r.backup_authority -and [bool]$c.restore_test_enabled -and (Has 'psql')){$x=Unprotect([string]$c.restore_test_db_url_protected);$r.restore_test_authority=($x -match '^postgres(ql)?://' -and $x -notmatch 'xdfsjztwgsbmabshzsjw');$x=$null}
 }catch{Log ('Backup config unavailable: '+$_.Exception.Message)}
 return $r
}
function EnsureBackupTools{
 foreach($n in @('bridgepoint_full_export_windows.ps1','bridgepoint_verify_backup_windows.ps1','bridgepoint_restore_test_windows.ps1','bridgepoint_state_export_windows.ps1')){$p=Join-Path $BackupToolDir $n;if(-not(Test-Path $p)-or((Get-Date)-(Get-Item $p).LastWriteTime).TotalHours-ge 12){$tmp=$p+'.tmp';Invoke-WebRequest -UseBasicParsing -TimeoutSec 60 -Uri "$BackupBaseUrl/$n" -OutFile $tmp;$t=Get-Content $tmp -Raw;if($t.Length-lt 500-or$t-notmatch 'BridgePoint'){Remove-Item $tmp -Force -ErrorAction SilentlyContinue;throw "Rejected backup tool payload: $n"};Move-Item $tmp $p -Force}}
}
function Latest([string]$d){if(-not(Test-Path $d)){return $null};Get-ChildItem $d -Directory -Filter 'BridgePoint-*'|Sort-Object LastWriteTime -Descending|Select-Object -First 1}
function RunBackup($cfg,[string]$token,$job,$rt){
 $id=[string]$job.job_id;$op=([string]$job.operation).ToUpperInvariant();if($op-notin@('EXPORT','VERIFY','RESTORE_TEST')){throw "Blocked operation $op"};EnsureBackupTools;$dest=[string]$rt.destination;if(-not$dest){throw 'Backup destination not configured locally.'};Log "Backup job $id / $op claimed."
 try{
  if($op-eq'EXPORT'){$c=$rt.config;$env:BRIDGEPOINT_BACKUP_DB_URL=Unprotect([string]$c.db_url_protected);$env:BRIDGEPOINT_BACKUP_S3_ACCESS_KEY_ID=Unprotect([string]$c.s3_access_key_protected);$env:BRIDGEPOINT_BACKUP_S3_SECRET_ACCESS_KEY=Unprotect([string]$c.s3_secret_key_protected);$env:BRIDGEPOINT_BACKUP_DESTINATION=$dest;$out=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $BackupToolDir 'bridgepoint_full_export_windows.ps1') -Destination $dest -NonInteractive 2>&1;if($LASTEXITCODE-ne 0){throw "Export exited ${LASTEXITCODE}: $($out|Select-Object -Last 8|Out-String)"};$b=Latest $dest;if(-not$b){throw 'No backup folder found after export.'};$m=Get-Content (Join-Path $b.FullName 'manifest.json') -Raw|ConvertFrom-Json;$res=@{backup_name=$b.Name;exported_at=$m.exported_at;archive_bytes=$m.primary_database_archive_bytes;storage_included=$m.storage_included;git_mirrors_included=$m.git_mirrors_included;format_version=$m.format_version}}
  elseif($op-eq'VERIFY'){$b=Latest $dest;if(-not$b){throw 'No backup exists to verify.'};$out=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $BackupToolDir 'bridgepoint_verify_backup_windows.ps1') -BackupRoot $b.FullName 2>&1;if($LASTEXITCODE-ne 0){throw "Verify exited ${LASTEXITCODE}: $($out|Select-Object -Last 8|Out-String)"};$v=Get-Content (Join-Path $b.FullName 'verification.json') -Raw|ConvertFrom-Json;$res=@{backup_name=$b.Name;verified=[bool]$v.verified;verified_at=$v.verified_at;archive_bytes=$v.archive_bytes;checksums=$v.checksums;pg_restore_catalog=$v.pg_restore_catalog}}
  else{if(-not$rt.restore_test_authority){throw 'Restore-test authority not configured locally.'};$b=Latest $dest;if(-not$b){throw 'No backup exists for restore testing.'};$env:BRIDGEPOINT_RESTORE_TEST_DB_URL=Unprotect([string]$rt.config.restore_test_db_url_protected);if($env:BRIDGEPOINT_RESTORE_TEST_DB_URL-match'xdfsjztwgsbmabshzsjw'){throw 'Production restore target blocked.'};$out=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $BackupToolDir 'bridgepoint_restore_test_windows.ps1') -BackupRoot $b.FullName -SkipData -NonInteractive 2>&1;if($LASTEXITCODE-ne 0){throw "Restore-test exited ${LASTEXITCODE}: $($out|Select-Object -Last 8|Out-String)"};$v=Get-Content (Join-Path $b.FullName 'restore-test.json') -Raw|ConvertFrom-Json;$res=@{backup_name=$b.Name;restore_test_passed=[bool]$v.restore_test_passed;tested_at=$v.tested_at;target_host=$v.target_host;schema_only=$v.schema_only}}
  $null=BP $cfg $token 'backup_complete' @{job_id=$id;result=$res};Log "Backup job $id / $op completed."
 }catch{$msg=$_.Exception.Message;try{$null=BP $cfg $token 'backup_fail' @{job_id=$id;error=$msg;result=@{operation=$op;agent_version=$AgentVersion}}}catch{};Log "Backup job $id / $op failed: $msg"}
 finally{Remove-Item Env:BRIDGEPOINT_BACKUP_DB_URL,Env:BRIDGEPOINT_BACKUP_S3_ACCESS_KEY_ID,Env:BRIDGEPOINT_BACKUP_S3_SECRET_ACCESS_KEY,Env:BRIDGEPOINT_BACKUP_DESTINATION,Env:BRIDGEPOINT_RESTORE_TEST_DB_URL -ErrorAction SilentlyContinue}
}
function RunPortableExport($cfg,[string]$token,$job,$rt){
 $id=[string]$job.request_id;$kind=([string]$job.scope_kind).ToUpperInvariant();$key=([string]$job.scope_key).ToUpperInvariant();if($kind-ne'STATE'-or$key-notmatch'^[A-Z]{2}$'){throw "Blocked portable export scope $kind/$key"};EnsureBackupTools
 $dest=Join-Path ([Environment]::GetFolderPath('UserProfile')) 'BridgePointStateExports';New-Item -ItemType Directory -Force -Path $dest|Out-Null;Log "Portable export $id / $kind $key claimed."
 try{
  $db=Unprotect([string]$rt.config.db_url_protected);if($db-notmatch'^postgres(ql)?://'){throw 'Protected production database URL is unavailable.'}
  $tool=Join-Path $BackupToolDir 'bridgepoint_state_export_windows.ps1';$out=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $tool -State $key -Destination $dest -DbUrl $db 2>&1;if($LASTEXITCODE-ne 0){throw "State export exited ${LASTEXITCODE}: $($out|Select-Object -Last 10|Out-String)"}
  $bundle=Get-ChildItem $dest -Directory -Filter ("BridgePoint-{0}-*" -f $key)|Sort-Object LastWriteTime -Descending|Select-Object -First 1;if(-not$bundle){throw 'No state export bundle found after exporter completed.'}
  $manifestPath=Join-Path $bundle.FullName 'manifest.json';$checks=Join-Path $bundle.FullName 'SHA256SUMS.txt';if(-not(Test-Path $manifestPath)-or-not(Test-Path $checks)){throw 'State export integrity files are missing.'}
  $m=Get-Content $manifestPath -Raw|ConvertFrom-Json;$files=@(Get-ChildItem $bundle.FullName -Recurse -File);$zip=$bundle.FullName+'.zip';$res=@{state_code=$key;bundle_name=$bundle.Name;bundle_path=$bundle.FullName;exported_at=$m.exported_at;portable_database=[bool]$m.portable_database;portable_database_file=[string]$m.portable_database_file;zip_created=(Test-Path $zip);zip_path=$(if(Test-Path $zip){$zip}else{''});file_count=$files.Count;checksum_file=$checks;format_version=$m.format_version;agent_version=$AgentVersion}
  $null=BP $cfg $token 'export_complete' @{request_id=$id;result=$res};Log "Portable export $id / $key completed: $($bundle.FullName)"
 }catch{$msg=$_.Exception.Message;try{$null=BP $cfg $token 'export_fail' @{request_id=$id;error=$msg;result=@{scope_kind=$kind;scope_key=$key;agent_version=$AgentVersion}}}catch{};Log "Portable export $id / $key failed: $msg"}
 finally{$db=$null}
}
function Ollama([string]$model,[array]$messages){$body=@{model=$model;messages=$messages;stream=$false;format='json';options=@{temperature=0.15;num_ctx=8192}}|ConvertTo-Json -Depth 30 -Compress;$r=Invoke-RestMethod -Method Post -Uri 'http://127.0.0.1:11434/api/chat' -ContentType 'application/json' -Body $body -TimeoutSec 900;$text=[string]$r.message.content;try{$text|ConvertFrom-Json}catch{@{summary=$text;parse_warning='MODEL_OUTPUT_WAS_NOT_JSON'}}}
function PrimaryMessages($task){$w=$task.worker;$sys="You are a local BridgePoint Intelligence reasoning worker. You are NOT the execution authority. Supabase remains authoritative for policy, permissions, security, money, external actions and verification. Never claim an action happened unless supplied evidence proves it. Never invent database state. Return JSON only with summary, findings, recommended_actions, evidence_needed, verification_tests, risks, confidence. Worker mission: $($w.mission). Guardrails: $($w.guardrails|ConvertTo-Json -Compress). Permissions: $($w.permissions|ConvertTo-Json -Compress).";@(@{role='system';content=$sys},@{role='user';content=("TASK TYPE: $($task.task_type)`nSECURITY CLASS: $($task.security_class)`nINPUT:`n"+($task.input|ConvertTo-Json -Depth 30))})}
function ReviewMessages($task,$primary){@(@{role='system';content="You are BridgePoint's independent local reviewer. Return JSON only with verdict, issues, unsupported_claims, security_concerns, missing_evidence, required_changes, verification_tests, confidence. Reject unsupported completion claims, credential exposure, destructive or regulated action, unauthorized messaging, or money movement."},@{role='user';content=("ORIGINAL TASK:`n"+($task.input|ConvertTo-Json -Depth 30)+"`nPRIMARY RESULT:`n"+($primary|ConvertTo-Json -Depth 30))})}
function CheckUpdate{try{$tmp=$AgentPath+'.update';Invoke-WebRequest -UseBasicParsing -TimeoutSec 45 -Uri $AgentUrl -OutFile $tmp;$txt=Get-Content $tmp -Raw;if($txt-notmatch '# BridgePoint Local Agent - signed channel live-artifact' -or $txt-notmatch '\$AgentVersion\s*=\s*(\d+)'){Remove-Item $tmp -Force -ErrorAction SilentlyContinue;return $false};$remote=[int]$Matches[1];if($remote-le$AgentVersion){Remove-Item $tmp -Force -ErrorAction SilentlyContinue;return $false};Move-Item $tmp $AgentPath -Force;Log "Installed agent update $remote; restarting.";Start-Process powershell.exe -ArgumentList "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$AgentPath`"" -WindowStyle Hidden;return $true}catch{Log ('Update check failed safely: '+$_.Exception.Message);return $false}}
$cfg=LoadCfg;$token=Unprotect([string]$cfg.token_protected);Log "BridgePoint Local AI starting. Node=$($cfg.node_id) Agent=$AgentVersion Primary=$($cfg.primary_model) Reviewer=$($cfg.reviewer_model)";$lastHeartbeat=[datetime]::MinValue;$lastUpdate=[datetime]::MinValue
while($true){try{if(((Get-Date)-$lastUpdate).TotalHours-ge 6){$lastUpdate=Get-Date;if(CheckUpdate){exit 0}};$rt=BackupRuntime;if(((Get-Date)-$lastHeartbeat).TotalSeconds-ge 45){$cap=@{provider='OLLAMA';primary_model=$cfg.primary_model;reviewer_model=$cfg.reviewer_model;agent_version=$AgentVersion;outbound_only=$true;execution_authority=$false;backup_authority=[bool]$rt.backup_authority;restore_test_authority=[bool]$rt.restore_test_authority;portable_export_authority=[bool]$rt.portable_export_authority;backup_protocol='ALLOWLIST_V717';portable_export_protocol='STATE_V936'};$null=BP $cfg $token 'heartbeat' @{capabilities=$cap;hardware=@{computer=$env:COMPUTERNAME;os=[Environment]::OSVersion.VersionString}};$lastHeartbeat=Get-Date};if($rt.backup_authority){$bc=BP $cfg $token 'backup_claim' @{};if($bc.job){RunBackup $cfg $token $bc.job $rt}};if($rt.portable_export_authority){$ec=BP $cfg $token 'export_claim' @{};if($ec.job){RunPortableExport $cfg $token $ec.job $rt}};try{$null=Invoke-RestMethod 'http://127.0.0.1:11434/api/tags' -TimeoutSec 5}catch{Log 'Ollama not responding; starting ollama serve.';Start-Process ollama -ArgumentList 'serve' -WindowStyle Hidden;Start-Sleep 4};$claim=BP $cfg $token 'claim' @{limit=[int]$cfg.claim_limit};$tasks=@($claim.tasks);foreach($task in $tasks){try{$p=Ollama ([string]$cfg.primary_model) (PrimaryMessages $task);$r=Ollama ([string]$cfg.reviewer_model) (ReviewMessages $task $p);$null=BP $cfg $token 'submit' @{task_id=[string]$task.task_id;primary=$p;reviewer=$r;models=@{provider='OLLAMA';primary=$cfg.primary_model;reviewer=$cfg.reviewer_model;agent_version=$AgentVersion;computer=$env:COMPUTERNAME}};Log "Submitted governed result for $($task.task_id)."}catch{$m=$_.Exception.Message;Log "Task failed $($task.task_id): $m";try{$null=BP $cfg $token 'fail' @{task_id=[string]$task.task_id;error=$m}}catch{}}};if($tasks.Count-eq 0){Start-Sleep 8}}catch{Log "Agent loop error: $($_.Exception.Message)";Start-Sleep 20}}
