(()=>{
'use strict';
const SUPA='https://xdfsjztwgsbmabshzsjw.supabase.co';const KEY='sb_publishable_lM9oWQeHjBmgOIiteeOicQ_PTyAeF25';const RPC=`${SUPA}/rest/v1/rpc/`;const AUTH=`${SUPA}/auth/v1`;const BUCKET='bridgepoint-growth-creatives';
const $=(s,r=document)=>r.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let currentToken=null,currentItems=[];
function findToken(){try{for(let i=0;i<localStorage.length;i++){const raw=localStorage.getItem(localStorage.key(i));if(!raw)continue;try{const x=JSON.parse(raw),seen=new Set(),walk=o=>{if(!o||typeof o!=='object'||seen.has(o))return null;seen.add(o);if(typeof o.access_token==='string'&&o.access_token.length>30)return o.access_token;for(const v of Object.values(o)){const r=walk(v);if(r)return r}return null};const hit=walk(x);if(hit)return hit}catch(_){}}}catch(_){}return null}
function saveAuth(d){if(!d?.access_token)return;try{localStorage.setItem('bp-sandbox-auth-v1986',JSON.stringify({access_token:d.access_token,refresh_token:d.refresh_token,expires_at:Math.floor(Date.now()/1000)+(d.expires_in||3600),user:d.user||null}))}catch(_){}currentToken=d.access_token}
async function rpc(name,body={}){const r=await fetch(RPC+name,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${currentToken}`,'Content-Type':'application/json',Accept:'application/json','Cache-Control':'no-cache'},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||`HTTP ${r.status}`);return d}
function status(el,msg,kind=''){el.className='admin-status'+(kind?' '+kind:'');el.textContent=msg}
async function verifyOwner(){if(!currentToken)return false;try{await rpc('bridgepoint_owner_access_status_v358');$('#owner-lock').hidden=true;$('#owner-console').hidden=false;await loadItems();return true}catch(e){status($('#owner-login-status'),'Owner verification required. Sign in with a platform-owner account.','bad');return false}}
async function login(email,password){const out=$('#owner-login-status');status(out,'Signing in…');try{const r=await fetch(`${AUTH}/token?grant_type=password`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.msg||d?.message||'Sign in failed');saveAuth(d);if(await verifyOwner())status(out,'Owner verified.','good')}catch(e){status(out,e.message,'bad')}}
function uuid(){return crypto?.randomUUID?.()||`media-${Date.now()}-${Math.random().toString(36).slice(2)}`}
async function uploadFile(file){if(!file)return null;if(file.size>50*1024*1024)throw new Error('This upload is larger than 50 MB. Use a YouTube/Vimeo/public media URL for longer content.');if(file.type!=='video/mp4')throw new Error('Direct upload currently accepts MP4 video only.');const path=`public-media/${new Date().toISOString().slice(0,10)}/${uuid()}.mp4`;const r=await fetch(`${SUPA}/storage/v1/object/${BUCKET}/${path}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${currentToken}`,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d?.message||d?.error||`Upload failed (${r.status})`)}return `${SUPA}/storage/v1/object/public/${BUCKET}/${path}`}
async function saveMedia(){const out=$('#media-status');status(out,'Saving…');try{const file=$('#media-file').files?.[0];let url=$('#media-url').value.trim();if(file){status(out,'Uploading MP4…');url=await uploadFile(file)}if(!url)throw new Error('Paste a media URL or select an MP4 file.');const d=await rpc('bridgepoint_owner_upsert_featured_media_v1986',{p_story_key:$('#media-key').value.trim()||null,p_title:$('#media-title').value.trim(),p_description:$('#media-description').value.trim()||null,p_media_kind:$('#media-kind').value,p_media_url:url,p_thumbnail_url:$('#media-thumb').value.trim()||null,p_source_name:$('#media-source').value.trim()||null,p_display_order:Number($('#media-order').value||100),p_publish:$('#media-publish').checked});status(out,d.status==='PUBLISHED'?'Published. The public feed is updated.':'Saved as draft.','good');$('#media-key').value=d.story_key||$('#media-key').value;$('#media-file').value='';$('#media-url').value=url;await loadItems()}catch(e){status(out,e.message,'bad')}}
function thumb(item){return item.thumbnail_url?`<img class="media-admin-thumb" src="${esc(item.thumbnail_url)}" alt="">`:`<div class="media-admin-thumb blank">${esc((item.media_kind||'media').toUpperCase())}</div>`}
function render(){const root=$('#media-admin-list');if(!currentItems.length){root.innerHTML='<div class="admin-status">No owner-managed public media yet. Add the first clip on the left.</div>';return}root.innerHTML=currentItems.map((x,i)=>`<div class="media-admin-item">${thumb(x)}<div class="media-admin-copy"><b>${esc(x.title)}</b><small>${esc(x.source_name||x.media_kind||'media')} · ${esc(x.status)} · order ${esc(x.display_order)}</small></div><div class="media-admin-actions"><button data-edit="${i}">Edit</button>${x.status==='PUBLISHED'?`<button data-unpub="${esc(x.story_key)}">Unpublish</button>`:''}</div></div>`).join('');root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editItem(currentItems[Number(b.dataset.edit)]));root.querySelectorAll('[data-unpub]').forEach(b=>b.onclick=()=>unpublish(b.dataset.unpub))}
function editItem(x){$('#media-key').value=x.story_key||'';$('#media-title').value=x.title||'';$('#media-description').value=x.description||'';$('#media-kind').value=x.media_kind||'video';$('#media-url').value=x.media_url||'';$('#media-thumb').value=x.thumbnail_url||'';$('#media-source').value=x.source_name||'';$('#media-order').value=x.display_order??100;$('#media-publish').checked=x.status==='PUBLISHED';scrollTo({top:0,behavior:'smooth'});$('#media-title').focus()}
async function unpublish(k){if(!confirm('Unpublish this media item from the public homepage?'))return;try{await rpc('bridgepoint_owner_unpublish_featured_media_v1986',{p_story_key:k});await loadItems()}catch(e){status($('#media-status'),e.message,'bad')}}
async function loadItems(){try{const d=await rpc('bridgepoint_owner_featured_media_v1986');currentItems=d.items||[];render()}catch(e){status($('#media-status'),e.message,'bad')}}
function stars(){const c=$('#cosmos');if(!c)return;const x=c.getContext('2d');let w,h,d=1,t=0;function size(){d=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*d;c.height=h*d;c.style.width=w+'px';c.style.height=h+'px';x.setTransform(d,0,0,d,0,0)}function draw(){x.clearRect(0,0,w,h);for(let i=0;i<90;i++){const px=((Math.sin(i*12.9898)*43758.5453)%1+1)%1*w,py=((Math.sin(i*7.223+4)*23421.21)%1+1)%1*h,a=.08+.15*(.5+.5*Math.sin(t*.003+i));x.fillStyle=`rgba(220,242,255,${a})`;x.beginPath();x.arc(px,py,i%17?0.5:1.2,0,Math.PI*2);x.fill()}t+=16;requestAnimationFrame(draw)}addEventListener('resize',size,{passive:true});size();draw()}
$('#owner-login').addEventListener('submit',e=>{e.preventDefault();login($('#owner-email').value.trim(),$('#owner-password').value)});$('#media-form').addEventListener('submit',e=>{e.preventDefault();saveMedia()});stars();currentToken=findToken();if(currentToken)verifyOwner();
})();
