(()=>{
'use strict';
const SUPABASE='https://xdfsjztwgsbmabshzsjw.supabase.co';
const KEY='sb_publishable_lM9oWQeHjBmgOIiteeOicQ_PTyAeF25';
const TRACK=`${SUPABASE}/rest/v1/rpc/track_acquisition_event_v400`;
const GEO=`${SUPABASE}/functions/v1/bridgepoint-coarse-geo-v436`;
const VERSION=673;
const params=new URLSearchParams(location.search),path=location.pathname||'/';
const newId=()=>globalThis.crypto?.randomUUID?.()||`bp-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const stored=(store,key)=>{try{let v=store.getItem(key);if(!v){v=newId();store.setItem(key,v)}return v}catch(_){return newId()}};
const visitorId=stored(localStorage,'bp_visitor_id_v421'),sessionId=stored(sessionStorage,'bp_session_id_v421');
const referrerHost=(()=>{try{return document.referrer?new URL(document.referrer).hostname:null}catch(_){return null}})();
const normalize=v=>String(v||'').replace(/\s+/g,' ').trim().toLowerCase();
const onceKey='bp_funnel_once_v673';
const refKey='bp_referral_v670',refPattern=/^bp-[a-z0-9-]{3,80}$/i,REF_TTL=60*24*60*60*1000;
const snapshotKey='bp_last_snapshot_v673',toolRunKey='bp_free_tool_runs_v673',SNAPSHOT_TTL=48*60*60*1000;
function validRef(v){return refPattern.test(String(v||'').trim())}
function currentReferral(){
  const incoming=String(params.get('ref')||'').trim().toLowerCase();
  if(validRef(incoming)){
    try{localStorage.setItem(refKey,JSON.stringify({code:incoming,seen_at:Date.now(),expires_at:Date.now()+REF_TTL}))}catch(_){}
    return incoming;
  }
  try{
    const saved=JSON.parse(localStorage.getItem(refKey)||'null');
    if(saved&&validRef(saved.code)&&Number(saved.expires_at)>Date.now())return String(saved.code).toLowerCase();
    if(saved)localStorage.removeItem(refKey);
  }catch(_){}
  return null;
}
function researchContext(){
  try{
    const s=JSON.parse(localStorage.getItem(snapshotKey)||'null');
    const runs=Number(localStorage.getItem(toolRunKey)||0);
    if(!s||!s.seen_at||Date.now()-Number(s.seen_at)>SNAPSHOT_TTL)return {runs};
    return {runs,query:String(s.query||'').slice(0,120),address:String(s.address||s.query||'').slice(0,80),active:true};
  }catch(_){return {runs:0}}
}
const effectiveRef=currentReferral();
function once(k){try{const m=JSON.parse(sessionStorage.getItem(onceKey)||'{}');if(m[k])return false;m[k]=1;sessionStorage.setItem(onceKey,JSON.stringify(m));return true}catch(_){return true}}
let geo={};
async function loadGeo(){try{const c=sessionStorage.getItem('bp_coarse_geo_v436');if(c)geo=JSON.parse(c)||{}}catch(_){geo={}}if(geo.country_code)return geo;try{const r=await fetch(GEO,{method:'GET',cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',headers:{apikey:KEY,Accept:'application/json'}});if(r.ok){const d=await r.json();const country=String(d?.country_code||'').toUpperCase().slice(0,2),region=String(d?.region_code||'').toUpperCase().slice(0,2);geo={};if(/^[A-Z]{2}$/.test(country))geo.country_code=country;if(country==='US'&&/^[A-Z]{2}$/.test(region))geo.region_code=region;try{sessionStorage.setItem('bp_coarse_geo_v436',JSON.stringify(geo))}catch(_){}}}catch(_){}return geo}
async function send(eventType,metadata={}){try{await fetch(TRACK,{method:'POST',keepalive:true,headers:{apikey:KEY,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({p_event_type:eventType,p_visitor_id:visitorId,p_session_id:sessionId,p_page_path:`${location.pathname}${location.search}`.slice(0,256),p_platform:'WEB',p_referrer_host:referrerHost,p_utm_source:params.get('utm_source'),p_utm_medium:params.get('utm_medium'),p_utm_campaign:params.get('utm_campaign'),p_utm_content:params.get('utm_content'),p_referral_code:effectiveRef,p_auth_error_code:null,p_metadata:{capture_version:VERSION,visibility:document.visibilityState,source_hint:params.get('utm_source')||referrerHost||'direct/unknown',referral_persisted:Boolean(effectiveRef&&!params.get('ref')),...geo,...metadata}})})}catch(_){}}
function appMode(a){if(!(a instanceof HTMLAnchorElement))return null;const href=a.getAttribute('href')||'';if(!href.startsWith('/app'))return null;let u;try{u=new URL(href,location.origin)}catch(_){return null}const text=normalize(a.textContent||a.getAttribute('aria-label')||''),campaign=normalize(u.searchParams.get('utm_campaign'));if(u.searchParams.get('mode')==='signup'||/trial|signup|create.account/.test(campaign)||/start.*trial|free trial|create account|sign up|try bridgepoint|continue.*property/.test(text))return 'signup';if(u.searchParams.get('mode')==='signin'||campaign==='open_app'||/open app|open bridgepoint|sign in|existing user/.test(text))return 'signin';return null}
function normalizeLinks(){const rc=researchContext();for(const a of document.querySelectorAll('a[href]')){const raw=a.getAttribute('href')||'';let u;try{u=new URL(raw,location.origin)}catch(_){continue}if(u.origin!==location.origin)continue;const carries=/^\/(app|start-now|sample)(\/|$)/.test(u.pathname);if(carries&&effectiveRef&&!u.searchParams.has('ref'))u.searchParams.set('ref',effectiveRef);if(u.pathname.startsWith('/app')){const mode=appMode(a);if(mode){u.searchParams.set('mode',mode);a.dataset.bpAccountMode=mode}if(rc.active&&rc.query&&!u.searchParams.has('property_query'))u.searchParams.set('property_query',rc.query)}if(carries)a.href=`${u.pathname}${u.search}${u.hash}`}}
function optimizeHomepage(){if(path!=='/')return;const hero=document.querySelector('.hero');if(!hero)return;const h1=hero.querySelector('h1'),p=hero.querySelector('p'),actions=hero.querySelector('.actions'),fine=hero.querySelector('.fine');if(h1)h1.textContent='Know which properties deserve attention before you drive.';if(p)p.textContent='BridgePoint matches property records, weather, property changes and verified evidence into explainable opportunities for contractors, restoration teams, adjusters and property operators.';if(actions)actions.innerHTML='<a class="btn primary" data-bp-conversion="hero-trial" href="/app/?mode=signup&utm_source=homepage&utm_medium=hero&utm_campaign=start_trial_v673">Start the 7-day trial</a><a class="btn secondary" href="/free-tools/?utm_source=homepage&utm_medium=hero&utm_campaign=property_snapshot_v673">Try a property first</a>';if(fine)fine.textContent='Connecticut is customer-ready now · Stripe checkout · transparent 7-day trial · cancel before renewal.';const nav=document.querySelector('.links .open');if(nav){nav.textContent='Start 7-day trial';nav.setAttribute('href','/app/?mode=signup&utm_source=homepage&utm_medium=nav&utm_campaign=start_trial_v673')}
const proof=document.getElementById('live-proof'),deep=document.getElementById('deep-tech');if(proof&&deep&&deep.parentNode)deep.parentNode.insertBefore(proof,deep);
if(!document.getElementById('bp-v673-style')){const s=document.createElement('style');s.id='bp-v673-style';s.textContent='@media(max-width:700px){body{padding-bottom:66px}.bp-v673-sticky{position:fixed;left:10px;right:10px;bottom:10px;z-index:9999;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 12px;border:1px solid #36536e;border-radius:14px;background:rgba(7,17,31,.96);box-shadow:0 12px 35px rgba(0,0,0,.35)}.bp-v673-sticky span{font-size:.82rem;color:#c6d5e2}.bp-v673-sticky a{white-space:nowrap;padding:10px 12px;border-radius:9px;background:#1693ff;color:#fff;text-decoration:none;font-weight:800}}@media(min-width:701px){.bp-v673-sticky{display:none}}';document.head.appendChild(s)}
if(!document.querySelector('.bp-v673-sticky')){const rc=researchContext(),bar=document.createElement('div');bar.className='bp-v673-sticky';bar.innerHTML=rc.active&&rc.runs>=2?`<span>Continue ${String(rc.address||'this property').replace(/[<>&]/g,'').slice(0,38)} in BridgePoint</span><a href="/app/?mode=signup&utm_source=homepage&utm_medium=return_intent&utm_campaign=property_continue_v673">Continue</a>`:'<span>See BridgePoint on a real property</span><a href="/free-tools/?utm_source=homepage&utm_medium=mobile_sticky&utm_campaign=property_snapshot_v673">Try it</a>';document.body.appendChild(bar)}}
function injectReturnIntent(){const rc=researchContext();if(!rc.active||rc.runs<2||path.startsWith('/app')||document.querySelector('.bp-return-intent-v673'))return;const style=document.createElement('style');style.textContent='.bp-return-intent-v673{position:fixed;right:16px;bottom:16px;z-index:9998;max-width:420px;padding:13px 14px;border:1px solid #3c6788;border-radius:14px;background:rgba(6,16,28,.97);box-shadow:0 14px 40px #0008;color:#eaf5ff;font:14px/1.35 system-ui}.bp-return-intent-v673 a{display:inline-block;margin-left:8px;padding:9px 11px;border-radius:9px;background:#1693ff;color:#fff;text-decoration:none;font-weight:800}@media(max-width:700px){.bp-return-intent-v673{display:none}}';document.head.appendChild(style);const box=document.createElement('div');box.className='bp-return-intent-v673';const safe=String(rc.address||'this property').replace(/[<>&"']/g,'').slice(0,58);box.innerHTML=`You already checked <strong>${safe}</strong>.<a href="/app/?mode=signup&utm_source=return_intent&utm_medium=sitewide&utm_campaign=property_continue_v673">Continue in BridgePoint</a>`;document.body.appendChild(box);if(once('return-intent-view'))send('VALUE_VIEW',{surface:'return_intent',property_context:true,tool_runs:rc.runs})}
function init(){optimizeHomepage();normalizeLinks();injectReturnIntent();loadGeo().finally(()=>{let type='VALUE_VIEW',meta={surface:'public_page'};if(path==='/'){type='LANDING_VIEW';meta={surface:'homepage',variant:'conversion_v673'}}else if(path.startsWith('/articles'))meta={surface:'research'};else if(path.startsWith('/sample')){type='SAMPLE_VIEW';meta={surface:'territory_sample'}}else if(path.startsWith('/app')&&params.get('mode')==='signup'){type='SIGNUP_VIEW';meta={surface:'app_signup',variant:'conversion_v673'}}else if(path.startsWith('/app'))meta={surface:'app_entry',account_mode:params.get('mode')||'unspecified'};send(type,meta)})
const targets=['#how','#markets','#research','[data-bp-value]'].flatMap(s=>Array.from(document.querySelectorAll(s)));if('IntersectionObserver'in window&&targets.length){const o=new IntersectionObserver(es=>{for(const e of es){if(!e.isIntersecting||e.intersectionRatio<.45)continue;const id=e.target.id||e.target.getAttribute('data-bp-value')||'value-section';if(once(`value:${path}:${id}`))send('VALUE_VIEW',{surface:'homepage_section',section:id});o.unobserve(e.target)}},{threshold:[.45]});targets.forEach(t=>o.observe(t))}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target.closest('a,button'):null;if(!t)return;const text=normalize(t.textContent||t.getAttribute('aria-label')||''),href=t instanceof HTMLAnchorElement?t.getAttribute('href')||'':'';if(href.startsWith('/articles')||text.includes('research')||text.includes('brief'))send('VALUE_VIEW',{surface:'research_click',destination:href.slice(0,160)});if(href.startsWith('/sample')||text.includes('territory sample')||text.includes('sample'))send('SAMPLE_REQUEST',{surface:'public_cta',destination:href.slice(0,160)});const mode=t instanceof HTMLAnchorElement?(t.dataset.bpAccountMode||appMode(t)):null;if(mode==='signup'||/start.*trial|free trial|create account|sign up|continue.*property/.test(text))send('CREATE_ACCOUNT_CLICK',{surface:t.dataset.bpConversion||'public_cta',destination:href.slice(0,160),account_mode:'signup'});else if(href.startsWith('/app')||text.includes('open app')||text.includes('open bridgepoint')||text.includes('sign in'))send('VALUE_VIEW',{surface:'app_entry_click',destination:href.slice(0,160),account_mode:mode||'signin'});if(text.includes('pricing')||text.includes('plans')||text.includes('package'))send('PRICING_VIEW',{surface:'public_cta'})},{capture:true});
document.addEventListener('input',e=>{if(!path.startsWith('/app')||params.get('mode')!=='signup')return;const t=e.target;if(!(t instanceof HTMLInputElement||t instanceof HTMLSelectElement||t instanceof HTMLTextAreaElement))return;if(once('signup-form-start'))send('SIGNUP_FORM_START',{surface:'app_signup',field_type:t.type||t.tagName.toLowerCase(),variant:'conversion_v673'})},{capture:true});
document.addEventListener('submit',e=>{const form=e.target instanceof HTMLFormElement?e.target:null;if(!form)return;if(path.startsWith('/sample')||form.matches('[data-bp-sample-form]'))send('SAMPLE_REQUEST',{surface:'territory_form_submit'});if(path.startsWith('/app')&&params.get('mode')==='signup'&&once('signup-submit'))send('SIGNUP_SUBMIT',{surface:'app_signup',variant:'conversion_v673'})},{capture:true});
})();
