(()=>{
'use strict';
const SUPA='https://xdfsjztwgsbmabshzsjw.supabase.co';const KEY='sb_publishable_lM9oWQeHjBmgOIiteeOicQ_PTyAeF25';const $=s=>document.querySelector(s);
function visitor(){try{let v=localStorage.getItem('bp-enterprise-visitor-v1988');if(!v){v=crypto?.randomUUID?.()||`visitor-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem('bp-enterprise-visitor-v1988',v)}return v}catch(_){return `anon-${Date.now()}`}}
function setStatus(msg,kind=''){const el=$('#request-status');el.className='request-status'+(kind?' '+kind:'');el.textContent=msg}
async function submit(){setStatus('Sending request…');const name=$('#req-name').value.trim(),email=$('#req-email').value.trim(),company=$('#req-company').value.trim(),type=$('#req-type').value,scale=$('#req-scale').value,geo=$('#req-geo').value.trim(),use=$('#req-use').value.trim(),integrations=$('#req-integrations').value.trim(),notes=$('#req-notes').value.trim(),website=$('#req-website').value.trim();const body=[`Requested access: ${type}`,`Expected scale: ${scale}`,`Geography: ${geo||'Not specified'}`,`Primary use case: ${use}`,`Systems / integrations: ${integrations||'Not specified'}`,notes?`Additional context: ${notes}`:''].filter(Boolean).join('\n\n');try{const r=await fetch(`${SUPA}/rest/v1/rpc/bridgepoint_message_owner_v556`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({p_body:body,p_display_name:name,p_email:email,p_company:company||null,p_subject:'Enterprise / API Access Request',p_intent:'SALES',p_visitor_id:visitor(),p_website:website||null})});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error==='RATE_LIMITED'?'Too many requests. Please wait before trying again.':d.error||`Request failed (${r.status})`);setStatus('Request delivered to BridgePoint. No credentials or charges were created.','good');$('#enterprise-form').reset()}catch(e){setStatus(e.message,'bad')}}
function cosmos(){const c=$('#cosmos');if(!c)return;const x=c.getContext('2d');let w=0,h=0,d=1,t=0;const f=v=>v-Math.floor(v);function size(){d=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*d;c.height=h*d;c.style.width=w+'px';c.style.height=h+'px';x.setTransform(d,0,0,d,0,0)}function draw(){x.clearRect(0,0,w,h);const cx=w*.52,cy=h*.43,r=Math.max(126,Math.min(w,h)*.285),pulse=.5+.5*Math.sin(t*.016);for(let i=0;i<110;i++){const px=f(Math.sin(i*12.9898+1.7)*43758.5453)*w,py=f(Math.sin(i*8.233+4.1)*24634.6345)*h,a=.08+.18*(.5+.5*Math.sin(t*.003+i*1.7));x.fillStyle=`rgba(230,242,255,${a})`;x.beginPath();x.arc(px,py,i%23===0?1.2:.45,0,Math.PI*2);x.fill()}const g=x.createRadialGradient(cx,cy,r*.42,cx,cy,r*3.1);g.addColorStop(0,'rgba(0,0,0,.98)');g.addColorStop(.28,'rgba(0,0,0,.92)');g.addColorStop(.45,`rgba(139,92,246,${.11+pulse*.03})`);g.addColorStop(.65,'rgba(72,225,255,.05)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.beginPath();x.arc(cx,cy,r*3.1,0,Math.PI*2);x.fill();x.save();x.translate(cx,cy);x.rotate(-.18);for(let i=0;i<11;i++){x.beginPath();x.ellipse(0,0,r*(1.72+i*.05),r*(.35+i*.013),0,t*.00032+i*.02,t*.00032+i*.02+Math.PI*1.7);const hue=i%4===0?'255,201,94':i%2===0?'72,225,255':'139,92,246';x.strokeStyle=`rgba(${hue},${.08+i*.009})`;x.lineWidth=1+(i%3)*.5;x.stroke()}x.restore();x.fillStyle='#000';x.beginPath();x.arc(cx,cy,r*.69,0,Math.PI*2);x.fill();x.strokeStyle=`rgba(72,225,255,${.19+pulse*.07})`;x.lineWidth=2;x.beginPath();x.arc(cx,cy,r*.82,0,Math.PI*2);x.stroke();t+=16;requestAnimationFrame(draw)}addEventListener('resize',size,{passive:true});size();draw()}
$('#enterprise-form').addEventListener('submit',e=>{e.preventDefault();submit()});cosmos();
})();
