(()=>{
'use strict';
if(window.__bridgepointLanguageV2000)return;window.__bridgepointLanguageV2000=true;
const KEY='bp-language-v2000';
const LANGS=[
['en','English'],['es','Español'],['fr','Français'],['de','Deutsch'],['it','Italiano'],['pt','Português'],['nl','Nederlands'],['pl','Polski'],['ro','Română'],['sv','Svenska'],['no','Norsk'],['da','Dansk'],['fi','Suomi'],['cs','Čeština'],['el','Ελληνικά'],['tr','Türkçe'],['ru','Русский'],['uk','Українська'],['ar','العربية'],['he','עברית'],['hi','हिन्दी'],['bn','বাংলা'],['ur','اردو'],['zh-CN','中文（简体）'],['ja','日本語'],['ko','한국어'],['vi','Tiếng Việt']
];
const VALID=new Set(LANGS.map(x=>x[0]));
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function chosen(){let q=null;try{q=new URL(location.href).searchParams.get('lang')}catch(_){};if(q&&VALID.has(q)){try{localStorage.setItem(KEY,q)}catch(_){};return q}try{const v=localStorage.getItem(KEY);if(v&&VALID.has(v))return v}catch(_){}return'en'}
function setCookie(lang){const expires='; Max-Age=31536000; Path=/; SameSite=Lax';document.cookie=`bp_lang=${encodeURIComponent(lang)}${expires}`;if(lang==='en'){
 document.cookie='googtrans=; Max-Age=0; Path=/';
 if(location.hostname.endsWith('bridgepointintelligence.online'))document.cookie='googtrans=; Max-Age=0; Path=/; Domain=.bridgepointintelligence.online';
}else{
 const v=`/en/${lang}`;document.cookie=`googtrans=${v}${expires}`;
 if(location.hostname.endsWith('bridgepointintelligence.online'))document.cookie=`googtrans=${v}${expires}; Domain=.bridgepointintelligence.online`;
}}
function save(lang){if(!VALID.has(lang))lang='en';try{localStorage.setItem(KEY,lang)}catch(_){};setCookie(lang);document.documentElement.lang=lang;document.documentElement.dir=['ar','he','ur'].includes(lang)?'rtl':'ltr';return lang}
function protectRaw(root=document){const selectors=['#result-address','#result-meta','#permit-items','#propertyAddress','#propertyMeta','#mapResults','#globalSearchResults','.property-grid .fact-card b','.timeline-item p','.data-card .fact-card b','.bp-popup','.map-drawer h2','.map-drawer p','input','textarea','code','pre'];for(const sel of selectors)for(const el of $$(sel,root)){el.classList.add('notranslate');el.setAttribute('translate','no')}}
function style(){if($('#bpLanguageStyleV2000'))return;const s=document.createElement('style');s.id='bpLanguageStyleV2000';s.textContent=`
.bp-language-picker{display:inline-flex;align-items:center;gap:6px;min-height:34px;padding:0 9px;border:1px solid rgba(118,225,255,.17);border-radius:999px;background:rgba(4,15,26,.78);color:#dffaff;backdrop-filter:blur(12px);font:800 11px/1 system-ui;white-space:nowrap;direction:ltr!important}
.bp-language-picker>span{font-size:14px}.bp-language-picker select{max-width:132px;border:0;outline:0;background:transparent;color:inherit;font:800 11px/1.2 system-ui;cursor:pointer;color-scheme:dark}.bp-language-picker option{background:#07131e;color:#eafdff}.bp-language-host{position:fixed!important;left:-10000px!important;top:-10000px!important;width:1px!important;height:1px!important;overflow:hidden!important}.bp-language-legal-note{margin:10px 0;padding:10px 12px;border:1px solid rgba(255,201,94,.18);border-radius:10px;background:rgba(255,201,94,.055);color:#d8c99b;font-size:10px;line-height:1.45}.goog-te-banner-frame,.goog-te-menu-frame,.VIpgJd-ZVi9od-ORHb-OEVmcd,iframe.skiptranslate{display:none!important}body{top:0!important}.goog-logo-link,.goog-te-gadget{display:none!important}
@media(max-width:680px){.bp-language-picker{padding:0 7px}.bp-language-picker select{max-width:92px;font-size:10px}.top-actions .bp-language-picker{order:-1}}
`;document.head.appendChild(s)}
function mount(){style();if($('#bpLanguagePickerV2000'))return;const lang=chosen();const lab=document.createElement('label');lab.id='bpLanguagePickerV2000';lab.className='bp-language-picker notranslate';lab.setAttribute('translate','no');lab.title='Choose language';lab.innerHTML=`<span aria-hidden="true">🌐</span><select aria-label="Language">${LANGS.map(([c,n])=>`<option value="${c}" ${c===lang?'selected':''}>${n}</option>`).join('')}</select>`;const pub=$('.top-actions'),app=$('.topbar');if(pub)pub.prepend(lab);else if(app){const target=$('#topSearch',app)||$('#notificationButton',app)||app.lastElementChild;app.insertBefore(lab,target||null)}else document.body.prepend(lab);lab.querySelector('select').addEventListener('change',e=>{const next=save(e.target.value);const u=new URL(location.href);u.searchParams.set('lang',next);location.replace(u.pathname+u.search+u.hash)});let host=$('#bpGoogleTranslateHostV2000');if(!host){host=document.createElement('div');host.id='bpGoogleTranslateHostV2000';host.className='bp-language-host notranslate';host.setAttribute('translate','no');document.body.appendChild(host)};protectRaw();if(lang!=='en')addLegalNotice();}
function addLegalNotice(){const lang=chosen();if(lang==='en')return;for(const card of ['#legal-modal .legal-card','#legalGate .legal-card','#legalGate'].map(s=>$(s)).filter(Boolean)){if($('.bp-language-legal-note',card))continue;const p=document.createElement('p');p.className='bp-language-legal-note';p.textContent='Translation is provided for convenience. For legal terms, source records, property addresses, parcel identifiers and other authoritative details, verify the original English/source record before making a material decision.';const h=card.querySelector('h2');(h||card.firstChild)?.insertAdjacentElement?.('afterend',p)}}
function applyCombo(lang,tries=0){const combo=$('.goog-te-combo');if(combo){if(combo.value!==lang){combo.value=lang;combo.dispatchEvent(new Event('change',{bubbles:true}))}return}if(tries<40)setTimeout(()=>applyCombo(lang,tries+1),150)}
function loadGoogle(){const lang=chosen();if(lang==='en')return;window.bpGoogleTranslateInitV2000=()=>{try{new google.translate.TranslateElement({pageLanguage:'en',includedLanguages:LANGS.filter(x=>x[0]!=='en').map(x=>x[0]).join(','),autoDisplay:false},'bpGoogleTranslateHostV2000');setTimeout(()=>applyCombo(lang),150)}catch(e){console.warn('BridgePoint translation init',e)}};if(!document.querySelector('script[data-bp-google-translate]')){const s=document.createElement('script');s.src='https://translate.google.com/translate_a/element.js?cb=bpGoogleTranslateInitV2000';s.async=true;s.dataset.bpGoogleTranslate='1';s.onerror=()=>console.warn('BridgePoint translation service unavailable; language preference remains saved.');document.head.appendChild(s)}}
function observe(){const mo=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1){protectRaw(n);if(chosen()!=='en'&&(n.matches?.('#legal-modal,#legalGate')||n.querySelector?.('#legal-modal,#legalGate')))addLegalNotice()}});mo.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('pagehide',()=>mo.disconnect(),{once:true})}
function init(){const lang=save(chosen());mount();observe();loadGoogle();window.BridgePointLanguageV2000={languages:LANGS,current:()=>chosen(),set:save,count:LANGS.length};document.dispatchEvent(new CustomEvent('bp:language-ready',{detail:{language:lang,count:LANGS.length}}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();