(()=>{
'use strict';
if(window.__bridgepointPublicV1994)return;window.__bridgepointPublicV1994=true;
const V=1994,SUPA='https://xdfsjztwgsbmabshzsjw.supabase.co',KEY='sb_publishable_lM9oWQeHjBmgOIiteeOicQ_PTyAeF25';
const RPC=`${SUPA}/rest/v1/rpc/`;
let legalIntent='signup',legalDocs=[],locked=false,lockY=0,lastAddress=0;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const comma=n=>Number(n||0).toLocaleString('en-US');
async function anonRpc(name,args={}){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),8000);try{const r=await fetch(RPC+name,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify(args),cache:'no-store',signal:ctl.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||`HTTP ${r.status}`);return d}finally{clearTimeout(t)}}
function installStyle(){const s=document.createElement('style');s.id='bp1994-public-style';s.textContent=`html,body{width:100%!important;max-width:100%!important;overflow-x:clip!important;overscroll-behavior-x:none!important;background:#000!important}body{touch-action:pan-y;background:transparent!important}#cosmos{opacity:.9!important;mix-blend-mode:screen!important}.counter-wrap,.bp1994-address,.modal{overflow-anchor:none}.bp1994-counter-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:24px;align-items:end;width:100%;max-width:100%}.bp1994-address{margin:22px 0 10px;min-width:0}.bp1994-address .counter-label{display:block;color:#8aa8ba;font-size:10px;font-weight:900;letter-spacing:1.4px}.bp1994-address strong{display:block;font-size:clamp(2.8rem,6.7vw,6.1rem);line-height:.9;letter-spacing:-.06em;background:linear-gradient(100deg,#fff,#7ce9ff 48%,#9eaaff);-webkit-background-clip:text;background-clip:text;color:transparent;font-variant-numeric:tabular-nums;white-space:nowrap}.bp1994-address small{display:block;color:#7e9aab;margin-top:8px;font-size:11px}.bp1994-proof{display:inline-flex;align-items:center;gap:6px;padding:7px 9px;border:1px solid rgba(69,230,166,.25);border-radius:999px;background:rgba(69,230,166,.075);color:#9bffd0;font-size:9px;font-weight:950}.bp1994-proof i{width:6px;height:6px;border-radius:50%;background:#45e6a6;box-shadow:0 0 12px rgba(69,230,166,.8)}.modal.show{overscroll-behavior:contain}.modal-card{max-height:min(88dvh,760px)!important;overflow:auto!important;overscroll-behavior:contain!important}.modal-card input,.modal-card select,.modal-card button{touch-action:manipulation}@media(max-width:720px){.bp1994-counter-grid{grid-template-columns:1fr;gap:0}.bp1994-address{margin:4px 0 12px}.bp1994-address strong{font-size:clamp(2.55rem,12.5vw,4.3rem)}.section-shell{width:calc(100% - 18px)!important}.hero{grid-template-columns:1fr!important;gap:20px!important}.hero-visual{min-height:390px!important}.canonical-core{width:min(390px,88vw)!important}.modal-card{width:calc(100vw - 18px)!important;margin:9px!important}}`;document.head.appendChild(s)}
function buildCounters(){const parcel=$('.counter-wrap');if(parcel&&!$('#address-counter')){const parent=document.createElement('div');parent.className='bp1994-counter-grid';parcel.parentNode.insertBefore(parent,parcel);parent.appendChild(parcel);const box=document.createElement('div');box.className='bp1994-address';box.innerHTML='<span class="counter-label">ADDRESS RECORDS CONNECTED</span><strong id="address-counter">Loading…</strong><small id="address-counter-meta">Live national address foundation</small>';parent.appendChild(box)}const strip=$('.proof-strip');if(strip){for(const x of $$('span',strip))if(/3-sec/i.test(x.textContent||''))x.textContent=x.textContent.replace(/3-sec live aggregate pulse/ig,'Quiet live aggregate pulse');if(!$('#jurisdiction-proof-v1994')){const p=document.createElement('span');p.id='jurisdiction-proof-v1994';p.className='bp1994-proof';p.innerHTML='<i></i><b>U.S. jurisdiction coverage loading…</b>';strip.prepend(p)}}}
async function refreshPulse(){if(document.hidden||$('.modal.show'))return;try{const d=await anonRpc('bridgepoint_public_system_pulse_v1992'),n=Number(d.total_addresses||0),el=$('#address-counter');if(el&&n&&n!==lastAddress){el.textContent=comma(n);lastAddress=n}if($('#address-counter-meta'))$('#address-counter-meta').textContent='live national address foundation · updates quietly';if($('#jurisdiction-proof-v1994 b'))$('#jurisdiction-proof-v1994 b').textContent=d.jurisdiction_coverage_label||'100% of U.S. state + D.C. jurisdictions represented'}catch(_){if($('#address-counter')&&!lastAddress)$('#address-counter').textContent='Live counter'}}
function lockPage(){if(locked)return;locked=true;lockY=scrollY||0;document.documentElement.style.scrollBehavior='auto';Object.assign(document.body.style,{position:'fixed',top:`-${lockY}px`,left:'0',right:'0',width:'100%',overflow:'hidden'})}
function unlockPage(){if(!locked)return;locked=false;Object.assign(document.body.style,{position:'',top:'',left:'',right:'',width:'',overflow:''});scrollTo(0,lockY);requestAnimationFrame(()=>document.documentElement.style.scrollBehavior='smooth')}
function show(id){$$('.modal.show').forEach(m=>{m.classList.remove('show');m.setAttribute('aria-hidden','true')});const m=$(id);if(!m)return;m.classList.add('show');m.setAttribute('aria-hidden','false');lockPage()}
async function loadLegal(){const root=$('#legal-docs');if(!root||legalDocs.length)return;if(root)root.innerHTML='<div class="loading-line">Loading current required documents…</div>';try{const d=await anonRpc('bridgepoint_public_legal_preview_v1054');legalDocs=Array.isArray(d.required_documents)?d.required_documents:[];root.innerHTML=legalDocs.map(x=>`<details><summary>${esc(x.title)} · ${esc(x.document_version)}</summary><div class="doc-copy"><b>${esc(x.summary||'')}</b>\n\n${esc(x.content_markdown||'')}</div></details>`).join('')||'<div class="loading-line">No active required documents returned.</div>'}catch(e){root.innerHTML=`<div class="loading-line">Legal registry could not load: ${esc(e.message)}</div>`}}
function setIntent(intent){legalIntent=intent==='signin'?'signin':'signup';try{sessionStorage.setItem('bp-legal-intent-v1994',legalIntent)}catch(_){}}
async function openLegal(intent){setIntent(intent);for(const id of ['ack-terms','ack-fcra','ack-verify'])if($('#'+id))$('#'+id).checked=false;if($('#continue-account'))$('#continue-account').disabled=true;show('#legal-modal');await loadLegal()}
function legalOkay(){return !!($('#ack-terms')?.checked&&$('#ack-fcra')?.checked&&$('#ack-verify')?.checked)}
function recordHandshake(){const payload={version:V,accepted_at:new Date().toISOString(),intent:legalIntent,document_keys:legalDocs.filter(x=>x.required!==false).map(x=>x.document_key),fcra_restriction:true,independent_verification:true};try{sessionStorage.setItem('bp-public-legal-handshake-v1994',JSON.stringify(payload))}catch(_){}}
function continueAfterLegal(){if(!legalOkay())return;recordHandshake();if(legalIntent==='signin')show('#signin-modal');else show('#account-modal')}
function intercept(e){const start=e.target.closest?.('[data-start-account]');const signin=e.target.closest?.('[data-open-signin],#switch-signin');const cont=e.target.closest?.('#continue-account');if(start){e.preventDefault();e.stopImmediatePropagation();void openLegal('signup');return}if(signin){e.preventDefault();e.stopImmediatePropagation();void openLegal('signin');return}if(cont){e.preventDefault();e.stopImmediatePropagation();continueAfterLegal();return}}
function bind(){document.addEventListener('click',intercept,true);document.addEventListener('change',e=>{if(['ack-terms','ack-fcra','ack-verify'].includes(e.target.id)&&$('#continue-account'))$('#continue-account').disabled=!legalOkay()},true);const mo=new MutationObserver(()=>{$('.modal.show')?lockPage():unlockPage()});$$('.modal').forEach(m=>mo.observe(m,{attributes:true,attributeFilter:['class','aria-hidden']}))}
async function wakePwa(){if(!('serviceWorker'in navigator))return;try{const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs)if(String(r.scope||'').includes('/app/'))await r.update().catch(()=>{})}catch(_){}}
function entryIntent(){const u=new URL(location.href);if(u.searchParams.get('signin')==='1'||u.searchParams.get('mode')==='signin')setTimeout(()=>openLegal('signin'),200)}
function init(){installStyle();buildCounters();bind();refreshPulse();setInterval(refreshPulse,30000);entryIntent();wakePwa()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();