(()=>{
'use strict';
if(window.__bridgepointPublicV1993)return;window.__bridgepointPublicV1993=true;
const SUPA='https://xdfsjztwgsbmabshzsjw.supabase.co',KEY='sb_publishable_lM9oWQeHjBmgOIiteeOicQ_PTyAeF25';
let lastAddress=0,locked=false,lockY=0;
const comma=n=>Number(n||0).toLocaleString('en-US');
function installStyle(){const s=document.createElement('style');s.textContent=`
html,body{width:100%!important;max-width:100%!important;overflow-x:hidden!important;overscroll-behavior-x:none!important;background:#000!important}body{touch-action:pan-y;background:transparent!important}body>*{max-width:100%}#cosmos{opacity:.88!important;mix-blend-mode:screen!important}.section-shell,.hero,.teaser,.media,.flow,.final-cta{min-width:0!important}.counter-wrap,.bp1993-address{overflow-anchor:none}.bp1993-counter-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:24px;align-items:end;width:100%;max-width:100%}.bp1993-counter-grid>.counter-wrap{margin:22px 0 10px}.bp1993-address{margin:22px 0 10px;min-width:0}.bp1993-address .counter-label{display:block;color:#8aa8ba;font-size:10px;font-weight:900;letter-spacing:1.4px}.bp1993-address strong{display:block;font-size:clamp(2.8rem,6.7vw,6.1rem);line-height:.9;letter-spacing:-.06em;background:linear-gradient(100deg,#fff,#7ce9ff 48%,#9eaaff);-webkit-background-clip:text;background-clip:text;color:transparent;font-variant-numeric:tabular-nums;white-space:nowrap}.bp1993-address small{display:block;color:#7e9aab;margin-top:8px;font-size:11px}.bp1993-proof{display:inline-flex;align-items:center;gap:6px;padding:7px 9px;border:1px solid rgba(69,230,166,.25);border-radius:999px;background:rgba(69,230,166,.075);color:#9bffd0;font-size:9px;font-weight:950}.bp1993-proof i{width:6px;height:6px;border-radius:50%;background:#45e6a6;box-shadow:0 0 12px rgba(69,230,166,.8)}.bp1993-depth{display:block;color:#7690a2;font-size:9px;margin-top:5px}.modal{overflow-anchor:none}.modal.show{overscroll-behavior:contain}.modal-card{max-height:min(88dvh,760px)!important;overflow:auto!important;overscroll-behavior:contain!important}.modal-card input,.modal-card select,.modal-card button{touch-action:manipulation}@media(max-width:720px){.bp1993-counter-grid{grid-template-columns:1fr;gap:0}.bp1993-address{margin:4px 0 12px}.bp1993-address strong{font-size:clamp(2.55rem,12.5vw,4.3rem)}.section-shell{width:calc(100% - 18px)!important}.hero{grid-template-columns:1fr!important;gap:20px!important}.hero-visual{min-height:390px!important}.canonical-core{width:min(390px,88vw)!important}.modal-card{width:calc(100vw - 18px)!important;margin:9px!important}}
`;document.head.appendChild(s)}
function build(){const parcel=document.querySelector('.counter-wrap');if(parcel&&!document.querySelector('#address-counter')){const parent=document.createElement('div');parent.className='bp1993-counter-grid';parcel.parentNode.insertBefore(parent,parcel);parent.appendChild(parcel);const box=document.createElement('div');box.className='bp1993-address';box.innerHTML='<span class="counter-label">ADDRESS RECORDS CONNECTED</span><strong id="address-counter">Loading…</strong><small id="address-counter-meta">Live national address foundation</small>';parent.appendChild(box)}const strip=document.querySelector('.proof-strip');if(strip&&!document.querySelector('#jurisdiction-proof-v1993')){const proof=document.createElement('span');proof.id='jurisdiction-proof-v1993';proof.className='bp1993-proof';proof.innerHTML='<i></i><b>U.S. jurisdiction coverage loading…</b>';strip.prepend(proof);const depth=document.createElement('span');depth.id='jurisdiction-depth-v1993';depth.className='bp1993-depth';depth.textContent='Coverage depth continues expanding.';strip.insertAdjacentElement('afterend',depth)}}
async function refresh(){if(document.hidden||document.querySelector('.modal.show'))return;try{const r=await fetch(`${SUPA}/rest/v1/rpc/bridgepoint_public_system_pulse_v1992`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json','Cache-Control':'no-cache'},body:'{}',cache:'no-store'});if(!r.ok)throw new Error('pulse');const d=await r.json(),n=Number(d.total_addresses||0),el=document.querySelector('#address-counter');if(el&&n&&n!==lastAddress){el.textContent=comma(n);lastAddress=n}const meta=document.querySelector('#address-counter-meta');if(meta)meta.textContent='live national address foundation · updates quietly in the background';const proof=document.querySelector('#jurisdiction-proof-v1993 b');if(proof)proof.textContent=d.jurisdiction_coverage_label||'100% of U.S. state + D.C. jurisdictions represented';const depth=document.querySelector('#jurisdiction-depth-v1993');if(depth)depth.textContent=d.coverage_depth_note||'Jurisdiction representation is nationwide; parcel, address, imagery and intelligence depth continue expanding.'}catch(_){const el=document.querySelector('#address-counter');if(el&&!lastAddress)el.textContent='Live counter'}}
function lockPage(){if(locked)return;locked=true;lockY=window.scrollY||0;document.documentElement.style.scrollBehavior='auto';document.body.style.position='fixed';document.body.style.top=`-${lockY}px`;document.body.style.left='0';document.body.style.right='0';document.body.style.width='100%';document.body.style.overflow='hidden'}
function unlockPage(){if(!locked)return;locked=false;document.body.style.position='';document.body.style.top='';document.body.style.left='';document.body.style.right='';document.body.style.width='';document.body.style.overflow='';window.scrollTo(0,lockY);requestAnimationFrame(()=>document.documentElement.style.scrollBehavior='smooth')}
function watchModals(){const sync=()=>{const open=!!document.querySelector('.modal.show');if(open)lockPage();else unlockPage()};const mo=new MutationObserver(sync);document.querySelectorAll('.modal').forEach(m=>mo.observe(m,{attributes:true,attributeFilter:['class','aria-hidden']}));sync()}
function maybeSignin(){const u=new URL(location.href);if(u.searchParams.get('signin')==='1')setTimeout(()=>document.querySelector('[data-open-signin]')?.click(),200)}
async function wakePwa(){if(!('serviceWorker'in navigator))return;try{const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs)if(String(r.scope||'').includes('/app/'))await r.update().catch(()=>{})}catch(_){}}
function init(){installStyle();build();watchModals();refresh();setInterval(refresh,30000);maybeSignin();wakePwa()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();