(()=>{
'use strict';
if(window.__bridgepointPublicV1992)return;window.__bridgepointPublicV1992=true;
const SUPA='https://xdfsjztwgsbmabshzsjw.supabase.co',KEY='sb_publishable_lM9oWQeHjBmgOIiteeOicQ_PTyAeF25';
let shown=0;
const comma=n=>Number(n||0).toLocaleString('en-US');
function style(){const s=document.createElement('style');s.textContent=`
.bp1992-proof{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid rgba(69,230,166,.25);border-radius:999px;background:rgba(69,230,166,.075);color:#8ff3c2;font-size:10px;font-weight:950}.bp1992-proof i{width:7px;height:7px;border-radius:50%;background:#45e6a6;box-shadow:0 0 13px rgba(69,230,166,.8)}
.bp1992-address{margin-top:14px}.bp1992-address .counter-label{color:#8aa8ba;font-size:10px;font-weight:900;letter-spacing:1.4px}.bp1992-address strong{display:block;font-size:clamp(2.5rem,6vw,5.7rem);line-height:.92;letter-spacing:-.06em;background:linear-gradient(100deg,#fff,#7ce9ff 48%,#9eaaff);-webkit-background-clip:text;background-clip:text;color:transparent;font-variant-numeric:tabular-nums}.bp1992-address small{display:block;color:#7e9aab;margin-top:7px;font-size:11px}.bp1992-counter-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;align-items:end}.bp1992-counter-grid .counter-wrap{margin:22px 0 10px}.bp1992-depth{display:block;color:#7690a2;font-size:9px;margin-top:4px}@media(max-width:720px){.bp1992-counter-grid{grid-template-columns:1fr;gap:0}.bp1992-address{margin-top:5px}.bp1992-address strong{font-size:3rem}}
`;document.head.appendChild(s)}
function build(){const parcel=document.querySelector('.counter-wrap');if(parcel&&!document.querySelector('#address-counter')){const parent=document.createElement('div');parent.className='bp1992-counter-grid';parcel.parentNode.insertBefore(parent,parcel);parent.appendChild(parcel);const box=document.createElement('div');box.className='bp1992-address';box.innerHTML='<span class="counter-label">ADDRESS RECORDS CONNECTED</span><strong id="address-counter">Loading…</strong><small id="address-counter-meta">Live national address foundation</small>';parent.appendChild(box)}const strip=document.querySelector('.proof-strip');if(strip&&!document.querySelector('#jurisdiction-proof-v1992')){const proof=document.createElement('span');proof.id='jurisdiction-proof-v1992';proof.className='bp1992-proof';proof.innerHTML='<i></i><b>U.S. jurisdiction coverage loading…</b>';strip.prepend(proof);const depth=document.createElement('span');depth.id='jurisdiction-depth-v1992';depth.className='bp1992-depth';depth.textContent='Coverage depth continues expanding.';strip.insertAdjacentElement('afterend',depth)}}
function animate(to){const el=document.querySelector('#address-counter');if(!el)return;const from=shown||Math.max(0,to-75000),start=performance.now(),dur=850;function step(now){const p=Math.min(1,(now-start)/dur),e=1-Math.pow(1-p,3);shown=Math.round(from+(to-from)*e);el.textContent=comma(shown);if(p<1)requestAnimationFrame(step)}requestAnimationFrame(step)}
async function refresh(){try{const r=await fetch(`${SUPA}/rest/v1/rpc/bridgepoint_public_system_pulse_v1992`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json','Cache-Control':'no-cache'},body:'{}',cache:'no-store'});if(!r.ok)throw new Error('pulse');const d=await r.json();const n=Number(d.total_addresses||0);if(n)animate(n);const meta=document.querySelector('#address-counter-meta');if(meta)meta.textContent=`live database estimate · updated automatically${d.address_count_updated_at?' · source pulse '+new Date(d.address_count_updated_at).toLocaleDateString():''}`;const proof=document.querySelector('#jurisdiction-proof-v1992 b');if(proof)proof.textContent=d.jurisdiction_coverage_label||`${d.jurisdiction_coverage_pct||0}% of U.S. state + D.C. jurisdictions represented`;const depth=document.querySelector('#jurisdiction-depth-v1992');if(depth)depth.textContent=d.coverage_depth_note||'Jurisdiction representation is nationwide; parcel, address, imagery and intelligence depth continue expanding.';}catch(_){const el=document.querySelector('#address-counter');if(el&&!shown)el.textContent='Live counter';}}
function maybeSignin(){const u=new URL(location.href);if(u.searchParams.get('signin')==='1'){setTimeout(()=>document.querySelector('[data-open-signin]')?.click(),250)}}
function init(){style();build();refresh();setInterval(refresh,5000);maybeSignin()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();