const SUPA='https://xdfsjztwgsbmabshzsjw.supabase.co';
const KEY='sb_publishable_lM9oWQeHjBmgOIiteeOicQ_PTyAeF25';
const RPC=SUPA+'/rest/v1/rpc/';
const $=id=>document.getElementById(id);
const fmt=n=>Number(n||0).toLocaleString();
const pct=n=>Math.max(0,Math.min(100,Number(n||0)));
const headers={'apikey':KEY,'Content-Type':'application/json','Accept':'application/json','Cache-Control':'no-cache'};
async function rpc(name,args={},timeout=5000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(RPC+name,{method:'POST',headers,body:JSON.stringify(args),signal:c.signal,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||('HTTP '+r.status));return d}finally{clearTimeout(t)}}
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function setBar(id,v){const e=$(id);if(e)e.style.width=pct(v)+'%'}
let statusLast=null,world=null,statusTimer=null,tileTimer=null;
function statusLabel(s){if(s.layout_status==='COMPLETE')return 'BACKEND LIVE · LAYOUT INDEX CAUGHT UP';return 'BACKEND LIVE · MATERIALIZING';}
async function loadStatus(){try{const s=await rpc('bridgepoint_frontend_status_v5000',{},5000);statusLast=s;setText('liveStateText',statusLabel(s));setText('canonicalProperties',fmt(s.canonical_properties));setText('uniqueAddresses',fmt(s.unique_addresses));setText('archivedBuildings',fmt(s.archived_buildings));setText('mapReadyBuildings',fmt(s.map_ready_buildings));setText('layoutIndexed',fmt(s.layout_indexed_buildings));setText('archiveMapPct',Number(s.archive_map_pct||0).toFixed(2)+'%');setText('layoutMapPct',Number(s.layout_map_pct||0).toFixed(2)+'%');setBar('archiveMapBar',s.archive_map_pct);setBar('layoutMapBar',s.layout_map_pct);setText('parcelCoverage',String(s.parcel_fresh_jurisdictions)+' / '+String(s.parcel_required_jurisdictions)+' fresh');const r=s.parcel_remaining||{};setText('parcelTail','FL '+fmt(r.FL)+' · NY '+fmt(r.NY)+' · PR '+fmt(r.PR));setText('buildingParts',fmt(s.materialized_part_geometries));setText('exactPlans',fmt(s.exact_plan_matches));setText('backendUpdated',s.backend_updated_at?new Date(s.backend_updated_at).toLocaleTimeString():new Date().toLocaleTimeString());return s}catch(e){setText('liveStateText','BACKEND RETRYING');console.warn('status',e);return null}}
function closeSystem(){if(innerWidth<=760)$('systemPanel').style.display='none'}
$('togglePanel').onclick=()=>{$('systemPanel').style.display=$('systemPanel').style.display==='none'?'block':'block'};
$('closePanel').onclick=()=>{$('systemPanel').style.display='none'};
$('closeBuilding').onclick=()=>{$('buildingPanel').hidden=true};
async function bootMap(){const mod=await import('./world-v2300-map.js?v=5000');world=mod.initWorld();window.__BP_V5000_WORLD=world;return world}
function truthLabel(b){if(b.exact_layout_available)return b.exact_layout_current?'EXACT CURRENT PUBLIC PLAN':'EXACT HISTORIC PUBLIC PLAN';if(b.layout_tier==='SOURCE_BACKED_VERTICAL')return b.building_part_count>0?'SOURCE-BACKED BUILDING PARTS':'SOURCE-BACKED VERTICAL';if(b.layout_tier==='HEIGHT_DERIVED_VERTICAL')return 'HEIGHT-DERIVED STRUCTURE';return 'FOOTPRINT SHELL';}
function floorTruth(method){const m=String(method||'');if(m.includes('BUILDING_PART_NUM')||m==='SOURCE_NUM_FLOORS')return 'source-backed';if(m.includes('HEIGHT'))return 'derived from height';return 'shell fallback'}
async function showBuilding(lng,lat){const panel=$('buildingPanel');panel.hidden=false;setText('buildingTruthBadge','LOADING');try{const d=await rpc('bridgepoint_public_building_detail_v5000',{p_lng:lng,p_lat:lat,p_radius_m:140},3500);if(!d?.resolved){setText('buildingTruthBadge','NO BUILDING RESOLVED');return}const b=d.building||{};setText('buildingTitle','Building #'+b.building_id);setText('buildingTruthBadge',truthLabel(b));setText('bHeight',b.render_height_m?Number(b.render_height_m).toFixed(1)+' m':'—');setText('bFloors',b.floors??'—');setText('bFloorTruth',floorTruth(b.floor_count_method));setText('bParts',fmt(b.building_part_count));setText('bUnderground',fmt(b.underground_part_count));setText('bConfidence',b.source_confidence!=null?Math.round(Number(b.source_confidence)*100)+'%':'—');setText('bRoof',b.roof_shape||b.roof_material||'—');setText('bFacade',b.facade_material||'—');setText('bSource',b.source_key||'BridgePoint');setText('bSourceDate',b.source_updated_at?new Date(b.source_updated_at).toLocaleDateString():'Source date unavailable');setText('bTruthNote',d.truth_notice||'BridgePoint labels derived structure separately from exact public plans.')}catch(e){setText('buildingTruthBadge','DETAIL RETRY');setText('bTruthNote',e.message||String(e))}}
window.addEventListener('bp2300:building-click',e=>{const ll=e.detail?.lngLat;if(ll)showBuilding(ll.lng,ll.lat)});
$('publicSearchForm').addEventListener('submit',async e=>{e.preventDefault();const q=$('publicSearchInput').value.trim(),box=$('publicSearchResults');if(q.length<4)return;box.hidden=false;box.innerHTML='<button disabled>Searching BridgePoint…</button>';try{const d=await rpc('bridgepoint_public_search_v5000',{p_query:q,p_limit:8},3500),rows=d?.results||[];if(!rows.length){box.innerHTML='<button disabled>No exact address match yet. Try the street address without city/state.</button>';return}box.innerHTML='';for(const r of rows){const b=document.createElement('button');b.type='button';b.innerHTML='<b>'+String(r.full_address||'Address').replace(/[<>&]/g,'')+'</b><small>'+[r.municipality,r.state_code,r.parcel_number].filter(Boolean).join(' · ')+'</small>';b.onclick=()=>{box.hidden=true;if(world?.map&&Number.isFinite(+r.longitude)&&Number.isFinite(+r.latitude))world.map.easeTo({center:[+r.longitude,+r.latitude],zoom:17,pitch:62,bearing:-18,duration:700})};box.appendChild(b)}}catch(err){box.innerHTML='<button disabled>Search retry · '+String(err.message||err).replace(/[<>&]/g,'')+'</button>'}});
function refreshTiles(){const map=world?.map;if(!map)return;const pulse=Math.floor(Date.now()/30000);const edge=SUPA+'/functions/v1/bridgepoint-spatial-tile-v1957';try{const b=map.getSource('bpBuildings');if(b?.setTiles)b.setTiles([edge+'?layer=buildings&z={z}&x={x}&y={y}&limit=9000&pulse='+pulse]);const p=map.getSource('bpParcels');if(p?.setTiles)p.setTiles([edge+'?layer=parcels&z={z}&x={x}&y={y}&limit=9000&pulse='+pulse]);map.triggerRepaint()}catch(e){console.warn('tile pulse',e)}}
async function start(){await loadStatus();try{await bootMap()}catch(e){setText('mapStatus','Map start retry · '+e.message)}statusTimer=setInterval(loadStatus,5000);tileTimer=setInterval(refreshTiles,30000);setTimeout(refreshTiles,6000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=5000').catch(()=>{})}
start();
window.addEventListener('beforeunload',()=>{clearInterval(statusTimer);clearInterval(tileTimer)});