import * as THREE from 'three';
const ENDPOINT='https://xdfsjztwgsbmabshzsjw.supabase.co/functions/v1/bridgepoint-horizon-stream-v3020';
const $=id=>document.getElementById(id),root=$('world'),loadText=$('loadText'),errorBox=$('error'),errorText=$('errorText');
const p=new URLSearchParams(location.search),lat=Number(p.get('lat')||41.5623),lon=Number(p.get('lon')||-72.6506),span=Math.max(.75,Math.min(2.4,Number(p.get('span_km')||1.25)));
const scene=new THREE.Scene();scene.background=new THREE.Color(0x737e70);scene.fog=new THREE.FogExp2(0x70796c,.00072);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.08,2800);camera.up.set(0,0,1);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',stencil:false});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;root.appendChild(renderer.domElement);
const world=new THREE.Group();scene.add(world);const hemi=new THREE.HemisphereLight(0xcad5c1,0x263126,1.5);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffd69a,2.0);sun.position.set(-180,-110,240);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const player=new THREE.Group();scene.add(player);player.position.set(0,0,0);let data=null,centerLon=lon,centerLat=lat,yaw=0,pitch=-.08,moveX=0,moveY=0,sprint=false,last=performance.now(),frames=0,fpsT=performance.now(),lootCount=0,health=100,flash=false,storm=false,dayPhase=.62;
const interactables=[],infected=[],roadAnchors=[],buildingCenters=[];const rand=(s=>()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296))(913733);const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function fail(e){errorBox.hidden=false;errorText.textContent=String(e?.message||e);loadText.textContent='V2 startup failed';console.error(e)}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1500)}
function project(c){return new THREE.Vector2((c[0]-centerLon)*111320*Math.cos(centerLat*Math.PI/180),(c[1]-centerLat)*110540)}
function rings(g){if(!g)return[];if(g.type==='Polygon')return[g.coordinates?.[0]||[]];if(g.type==='MultiPolygon')return(g.coordinates||[]).map(x=>x?.[0]||[]);return[]}
function lines(g){if(!g)return[];if(g.type==='LineString')return[g.coordinates||[]];if(g.type==='MultiLineString')return g.coordinates||[];return[]}
function mat(color,rough=.85,metal=.02){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})}
function addSky(){const sky=new THREE.Mesh(new THREE.SphereGeometry(2200,18,10),new THREE.MeshBasicMaterial({color:0x869184,side:THREE.BackSide}));scene.add(sky);const cm=new THREE.MeshStandardMaterial({color:0xa5a69e,transparent:true,opacity:.37,roughness:1});for(let i=0;i<20;i++){const c=new THREE.Mesh(new THREE.SphereGeometry(18+rand()*30,8,5),cm);c.scale.z=.18;c.position.set((rand()-.5)*900,(rand()-.5)*800,120+rand()*100);scene.add(c)}}
function addGround(){const size=span*1450;const g=new THREE.PlaneGeometry(size,size,1,1),m=mat(0x59674e,1,0),mesh=new THREE.Mesh(g,m);mesh.receiveShadow=true;world.add(mesh);const patches=new THREE.InstancedMesh(new THREE.CircleGeometry(1,6),mat(0x43533e,1,0),1100),d=new THREE.Object3D();for(let i=0;i<1100;i++){d.position.set((rand()-.5)*size,(rand()-.5)*size,.01);d.scale.set(1+rand()*4,.6+rand()*2,1);d.rotation.z=rand()*6.28;d.updateMatrix();patches.setMatrixAt(i,d.matrix)}world.add(patches)}
function roadStrip(a,b,w,color,z=.03){const len=a.distanceTo(b);if(len<1)return;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,len),mat(color,.98,0));m.position.set((a.x+b.x)/2,(a.y+b.y)/2,z);m.rotation.z=Math.atan2(b.y-a.y,b.x-a.x)-Math.PI/2;m.receiveShadow=true;world.add(m)}
function addRoads(){let n=0;for(const row of data.transport||[]){for(const line of lines(row.geometry)){for(let i=1;i<line.length;i++){const a=project(line[i-1]),b=project(line[i]),len=a.distanceTo(b);if(len<3||len>700)continue;const w=Math.max(5,Math.min(12,Number(row.width_m||7)));roadStrip(a,b,w,0x282d2b,.035);const ang=Math.atan2(b.y-a.y,b.x-a.x),nx=-Math.sin(ang),ny=Math.cos(ang);roadStrip(a.clone().add(new THREE.Vector2(nx*(w/2+.8),ny*(w/2+.8))),b.clone().add(new THREE.Vector2(nx*(w/2+.8),ny*(w/2+.8))),1.1,0x77796f,.055);roadStrip(a.clone().add(new THREE.Vector2(-nx*(w/2+.8),-ny*(w/2+.8))),b.clone().add(new THREE.Vector2(-nx*(w/2+.8),-ny*(w/2+.8))),1.1,0x77796f,.055);if(len>24&&n%2===0){roadStrip(a,b,.11,0xc7b36c,.06);roadAnchors.push({x:(a.x+b.x)/2,y:(a.y+b.y)/2,a:ang,w})}n++}}}return n}
function buildingMaterial(id){const pal=[0x776b5f,0x8a7c69,0x6a7069,0x8c745f,0x655c54,0x77786e];return mat(pal[hash(id)%pal.length],.84,.03)}
function addBuildingDetails(cx,cy,w,d,h,id){const dark=mat(0x26383a,.28,.18);const floors=Math.min(10,Math.max(1,Math.floor(h/3.1))),cols=Math.min(10,Math.max(2,Math.floor(w/3.2)));for(let f=0;f<floors;f++)for(let i=0;i<cols;i++){if(hash(id+':'+f+':'+i)%100<32)continue;const win=new THREE.Mesh(new THREE.PlaneGeometry(Math.min(1.35,w/(cols+1)*.6),.78),dark);win.position.set(cx-w/2+(i+1)*w/(cols+1),cy-d/2-.01,1.55+f*3);win.rotation.x=Math.PI/2;world.add(win)}const door=new THREE.Mesh(new THREE.PlaneGeometry(1.05,2.05),mat(0x312920,.9,0));door.position.set(cx,cy-d/2-.02,1.02);door.rotation.x=Math.PI/2;world.add(door);interactables.push({type:'door',x:cx,y:cy-d/2-1.2,label:'ENTER'});if(h<14){const roof=new THREE.Mesh(new THREE.ConeGeometry(Math.max(w,d)*.7,2.4,4),mat(0x4c4037,.95,.03));roof.position.set(cx,cy,h+1.2);roof.rotation.z=Math.PI/4;world.add(roof)}if(h>7&&hash(id)%3===0){const chimney=new THREE.Mesh(new THREE.BoxGeometry(.65,.65,1.8),mat(0x51453e,.92,0));chimney.position.set(cx+w*.22,cy+d*.15,h+.9);world.add(chimney)}for(const sx of[-1,1]){const gutter=new THREE.Mesh(new THREE.BoxGeometry(w,.12,.12),mat(0x505755,.5,.35));gutter.position.set(cx,cy+sx*d/2,h-.15);world.add(gutter)}}
function addBuildings(){let count=0;for(const row of data.buildings||[]){for(const ring of rings(row.geometry)){if(ring.length<4)continue;const pts=ring.map(project),xs=pts.map(q=>q.x),ys=pts.map(q=>q.y),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),w=maxx-minx,d=maxy-miny;if(w<2||d<2||w>160||d>160)continue;const h=Number(row.height_m||0)>2?Math.min(105,Number(row.height_m)):4.8+(hash(row.id)%130)/10,cx=(minx+maxx)/2,cy=(miny+maxy)/2;const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,d,h),buildingMaterial(row.id));mesh.position.set(cx,cy,h/2+.08);mesh.castShadow=mesh.receiveShadow=true;world.add(mesh);addBuildingDetails(cx,cy,w,d,h,String(row.id||count));buildingCenters.push({x:cx,y:cy,h,w,d});count++;if(count>=650)return count}}return count}
function addVegetation(){const size=span*1250,tr=mat(0x4d3928,1,0),leaves=[mat(0x344d32,1,0),mat(0x405b38,1,0),mat(0x50633e,1,0)];for(let i=0;i<430;i++){const x=(rand()-.5)*size,y=(rand()-.5)*size;if(Math.hypot(x,y)<15)continue;const h=3+rand()*7,t=new THREE.Mesh(new THREE.CylinderGeometry(.1,.22,h,6),tr);t.rotation.x=Math.PI/2;t.position.set(x,y,h/2);world.add(t);const c=new THREE.Mesh(new THREE.ConeGeometry(.8+rand()*1.6,2.2+rand()*3.2,7),leaves[i%3]);c.position.set(x,y,h+1.1);world.add(c)}for(let i=0;i<180;i++){const b=new THREE.Mesh(new THREE.DodecahedronGeometry(.35+rand()*.65,0),leaves[(i+1)%3]);b.position.set((rand()-.5)*size,(rand()-.5)*size,.4);world.add(b)}}
function addStreetLife(){const poleMat=mat(0x303a35,.6,.4),signMat=mat(0x6e2b24,.65,.12);for(let i=0;i<Math.min(110,roadAnchors.length);i+=2){const a=roadAnchors[i],side=i%4<2?1:-1,nx=-Math.sin(a.a),ny=Math.cos(a.a),x=a.x+nx*side*(a.w/2+2.2),y=a.y+ny*side*(a.w/2+2.2);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.06,.08,4.5,6),poleMat);pole.rotation.x=Math.PI/2;pole.position.set(x,y,2.25);world.add(pole);const lamp=new THREE.Mesh(new THREE.BoxGeometry(.65,.22,.18),mat(0x49534e,.45,.45));lamp.position.set(x,y,4.45);world.add(lamp);if(i%6===0){const sign=new THREE.Mesh(new THREE.BoxGeometry(.7,.08,.7),signMat);sign.position.set(x+.35,y,2.25);world.add(sign)}}}
function addAbandonment(){const colors=[0x58473a,0x45514e,0x69433a,0x4c4d45];for(let i=0;i<50;i++){const a=roadAnchors[i%Math.max(1,roadAnchors.length)]||{x:(rand()-.5)*400,y:(rand()-.5)*400,a:rand()*6.28,w:7};const car=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(3.8,1.72,.72),mat(colors[i%colors.length],.82,.22));body.position.z=.52;car.add(body);const cab=new THREE.Mesh(new THREE.BoxGeometry(1.8,1.48,.66),mat(0x283536,.34,.3));cab.position.set(.15,0,1.12);car.add(cab);car.position.set(a.x+(rand()-.5)*18,a.y+(rand()-.5)*18,.02);car.rotation.z=a.a+(rand()-.5)*.45;world.add(car);if(i%4===0)interactables.push({type:'vehicle',x:car.position.x,y:car.position.y,label:'SEARCH VEHICLE'})}for(let i=0;i<220;i++){const d=new THREE.Mesh(new THREE.BoxGeometry(.15+rand()*.7,.15+rand()*.7,.08+rand()*.28),mat(0x51463b,1,.03));d.position.set((rand()-.5)*span*900,(rand()-.5)*span*900,.08);d.rotation.set(rand()*2,rand()*2,rand()*6);world.add(d)}}
function spawnInfected(){const skin=mat(0x6f7665,.9,0),cloth=mat(0x393a34,.95,0);const count=18;for(let i=0;i<count;i++){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.28,.78,4,6),cloth);body.rotation.x=Math.PI/2;body.position.z=.92;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.22,8,6),skin);head.position.z=1.68;g.add(head);g.position.set((rand()-.5)*360,(rand()-.5)*360,0);world.add(g);infected.push({g,s:1+rand()*.7,phase:rand()*6.28})}$('infected').textContent=count}
function addSurvivor(){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.33,.9,5,7),mat(0x263129,.9,0));body.rotation.x=Math.PI/2;body.position.z=1.02;g.add(body);const pack=new THREE.Mesh(new THREE.BoxGeometry(.5,.24,.66),mat(0x544936,1,0));pack.position.set(0,.28,1.12);g.add(pack);const head=new THREE.Mesh(new THREE.SphereGeometry(.22,8,6),mat(0x8f7560,.85,0));head.position.z=1.82;g.add(head);player.add(g)}
const flashlight=new THREE.SpotLight(0xfff0ca,0,38,.42,.55,1.5);camera.add(flashlight);flashlight.target.position.set(0,0,-4);camera.add(flashlight.target);scene.add(camera);
function nearest(){let best=null,dist=4.1;for(const q of interactables){const d=Math.hypot(player.position.x-q.x,player.position.y-q.y);if(d<dist){dist=d;best=q}}return best}
function use(){const q=nearest();if(!q){toast('Nothing close enough to use');return}if(q.type==='vehicle'){lootCount++;$('loot').textContent=lootCount;toast(hash(q.x+':'+q.y)%3===0?'Found spark plug':'Found cloth + canned food')}else if(q.type==='door'){lootCount++;$('loot').textContent=lootCount;toast('Entered structure preview · interior loot acquired')}}
function updateInfected(dt,t){for(const z of infected){const dx=player.position.x-z.g.position.x,dy=player.position.y-z.g.position.y,d=Math.hypot(dx,dy);if(d<42&&d>1.2){z.g.position.x+=dx/d*z.s*dt;z.g.position.y+=dy/d*z.s*dt;z.g.rotation.z=Math.atan2(dy,dx)-Math.PI/2}else{z.g.position.x+=Math.sin(t*.0005+z.phase)*.12*dt;z.g.position.y+=Math.cos(t*.0004+z.phase)*.12*dt}if(d<1.15){health=Math.max(0,health-7*dt);$('health').textContent=Math.round(health)}}}
function updateWorldLight(t){dayPhase=(dayPhase+dtGlobal*.002)%1;const sunAmt=Math.max(.12,Math.sin(dayPhase*Math.PI));sun.intensity=storm?1.05:1.2+sunAmt*1.2;hemi.intensity=storm?.72:1.15+sunAmt*.55;scene.background.set(storm?0x454c49:(dayPhase>.15&&dayPhase<.85?0x738071:0x172028));scene.fog.color.copy(scene.background);renderer.toneMappingExposure=storm?.68:.72+sunAmt*.35;$('time').textContent=dayPhase>.15&&dayPhase<.85?'DAY':'NIGHT';flashlight.intensity=flash?5.5:0}
let dtGlobal=0;function updateCamera(dt){const sp=(sprint?8.5:4.6)*dt,f=new THREE.Vector2(-Math.sin(yaw),Math.cos(yaw)),r=new THREE.Vector2(Math.cos(yaw),Math.sin(yaw));player.position.x+=(f.x*moveY+r.x*moveX)*sp;player.position.y+=(f.y*moveY+r.y*moveX)*sp;player.position.z=0;player.rotation.z=yaw;const target=player.position.clone().add(new THREE.Vector3(0,0,1.25)),back=new THREE.Vector3(Math.sin(yaw)*4.9,-Math.cos(yaw)*4.9,2.4+pitch*2.4);camera.position.lerp(target.clone().add(back),Math.min(1,dt*8));camera.lookAt(target.clone().add(new THREE.Vector3(-Math.sin(yaw)*8,Math.cos(yaw)*8,pitch*7)));const q=nearest();$('prompt').hidden=!q;if(q)$('prompt').textContent=q.label}
async function load(){const west=lon-span/111.32/2,east=lon+span/111.32/2,south=lat-span/110.54/2,north=lat+span/110.54/2,u=new URL(ENDPOINT);for(const [k,v] of Object.entries({west,east,south,north,state:'CT',span_km:span}))u.searchParams.set(k,String(v));const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('world stream '+r.status);data=await r.json();if(!data?.complete)throw new Error(data?.error||'incomplete world stream');centerLon=(data.bbox.west+data.bbox.east)/2;centerLat=(data.bbox.south+data.bbox.north)/2;addSky();addGround();const roads=addRoads(),buildings=addBuildings();addVegetation();addStreetLife();addAbandonment();addSurvivor();spawnInfected();loadText.textContent=`${buildings.toLocaleString()} source-backed structures · ${roads.toLocaleString()} road segments · survival world active`;window.BP_HORIZON_V2={ok:true,build:4100,buildings,roads,infected:infected.length,mobileSafe:true,visualRebuild:true};}
function animate(){requestAnimationFrame(animate);const now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;dtGlobal=dt;updateCamera(dt);updateInfected(dt,now);updateWorldLight(now);renderer.render(scene,camera);frames++;if(now-fpsT>900){$('fps').textContent=Math.round(frames*1000/(now-fpsT))+' FPS';frames=0;fpsT=now}}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});let looking=false,lx=0,ly=0;renderer.domElement.addEventListener('pointerdown',e=>{if(e.clientX<innerWidth*.4)return;looking=true;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!looking)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;yaw-=dx*.006;pitch=Math.max(-.42,Math.min(.32,pitch-dy*.0035))});renderer.domElement.addEventListener('pointerup',()=>looking=false);
const pad=$('movePad'),knob=$('moveKnob');let pid=null;function padMove(e){const q=pad.getBoundingClientRect(),dx=e.clientX-(q.left+q.width/2),dy=e.clientY-(q.top+q.height/2),m=q.width*.34,l=Math.hypot(dx,dy)||1,s=Math.min(1,m/l),x=dx*s,y=dy*s;knob.style.transform=`translate(${x}px,${y}px)`;moveX=x/m;moveY=-y/m}pad.addEventListener('pointerdown',e=>{pid=e.pointerId;pad.setPointerCapture(pid);padMove(e)});pad.addEventListener('pointermove',e=>{if(e.pointerId===pid)padMove(e)});pad.addEventListener('pointerup',()=>{pid=null;moveX=moveY=0;knob.style.transform='translate(0,0)'});$('runBtn').addEventListener('pointerdown',()=>sprint=true);$('runBtn').addEventListener('pointerup',()=>sprint=false);$('useBtn').addEventListener('click',use);$('lightBtn').addEventListener('click',()=>{flash=!flash;toast(flash?'Flashlight on':'Flashlight off')});$('weatherBtn').addEventListener('click',()=>{storm=!storm;scene.fog.density=storm?.0017:.00072;toast(storm?'Storm front active':'Storm cleared')});
const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')use();if(e.code==='KeyT')flash=!flash});addEventListener('keyup',e=>keys[e.code]=false);setInterval(()=>{moveX=(keys.KeyD?1:0)-(keys.KeyA?1:0);moveY=(keys.KeyW?1:0)-(keys.KeyS?1:0);sprint=!!(keys.ShiftLeft||keys.ShiftRight)},16);
load().then(animate).catch(fail);