(()=>{
'use strict';
if(window.__bridgepointAtmosphereV2200)return;window.__bridgepointAtmosphereV2200=true;
const VERSION=2200;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mix=(a,b,t)=>Math.round(a+(b-a)*t);
const rgb=(a,b,t)=>`rgb(${mix(a[0],b[0],t)},${mix(a[1],b[1],t)},${mix(a[2],b[2],t)})`;
const MOBILE=innerWidth<=760||/Android|iPhone|iPad/i.test(navigator.userAgent);
const LOW=Number(navigator.deviceMemory||4)<=3||Number(navigator.hardwareConcurrency||4)<=4;
let S=null,map=null,cloudCanvas=null,cloudGL=null,cloudProgram=null,cloudRAF=0,lastCloudFrame=0,pollTimer=0,explicitUntil=0;
let state={visibilityMiles:10,cloudCoveragePct:10,stormActive:false,stormIntensity:0,cloudAltitudeM:2200,timeOfDay:null,source:'DEFAULT',effectiveDrawDistanceMiles:60,lastUpdated:null};
let originals={buildingColor:null,buildingOpacity:null,satBrightnessMax:null,streetBrightnessMax:null};
function nearestObservation(){const wx=window.BridgePointWorldEffects?.getState?.()?.data;if(!wx||!Array.isArray(wx.observations)||!wx.observations.length||!map)return null;const c=map.getCenter();let best=null,bd=Infinity;for(const o of wx.observations){const lng=Number(o.lng),lat=Number(o.lat);if(!Number.isFinite(lng)||!Number.isFinite(lat))continue;const dx=(lng-c.lng)*Math.cos(c.lat*Math.PI/180),dy=lat-c.lat,d=dx*dx+dy*dy;if(d<bd){bd=d;best=o}}return best}
function activeStorm(){const wx=window.BridgePointWorldEffects?.getState?.()?.data;if(!wx||!Array.isArray(wx.alerts))return{active:false,intensity:0};let intensity=0;for(const a of wx.alerts){const p=a?.properties||{},t=String(p.event||p.prod_type||p.headline||'').toLowerCase(),sev=String(p.severity||p.severity_text||'').toLowerCase();if(/severe thunderstorm|tornado|hurricane|tropical storm|blizzard|ice storm|flash flood/.test(t)){let x=/extreme|cat(egory)?\s*[45]/.test(sev+' '+t)?1:/severe|cat(egory)?\s*3/.test(sev+' '+t)?.82:/moderate|warning/.test(sev+' '+t)?.62:.48;intensity=Math.max(intensity,x)}}return{active:intensity>0,intensity}}
function localHour(){if(state.timeOfDay!=null){const v=Number(state.timeOfDay);if(Number.isFinite(v))return((v%24)+24)%24}const lng=map?.getCenter?.().lng||0;const n=new Date();return((n.getUTCHours()+n.getUTCMinutes()/60+lng/15)%24+24)%24}
function autoState(){if(Date.now()<explicitUntil)return;const o=nearestObservation(),st=activeStorm();const vis=Number(o?.visibility_mi??o?.visibility_sm??o?.visibility),cloudRaw=Number(o?.cloud_fraction??o?.cloud_cover_fraction??o?.cloud_cover),cloudPct=Number.isFinite(cloudRaw)?(cloudRaw<=1?cloudRaw*100:cloudRaw):state.cloudCoveragePct;applyState({visibilityMiles:Number.isFinite(vis)?vis:state.visibilityMiles,cloudCoveragePct:cloudPct,stormActive:st.active,stormIntensity:st.intensity,source:o?'LIVE_OBSERVATION':'LIVE_ALERTS'},false)}
function effectiveDraw(vis){if(!Number.isFinite(vis))return 60;if(vis<.25)return .35;if(vis<.5)return .65;if(vis<1)return Math.max(.8,vis*1.25);if(vis<3)return 2.5+vis*1.8;if(vis<5)return 8+vis*2.2;return 60}
function skyPalette(){const h=localHour(),storm=clamp(state.stormIntensity,0,1);let top,horizon,fog,light;if(h<5.5||h>20){top=[4,9,24];horizon=[15,23,37];fog=[28,34,43];light=[102,122,145]}else if(h<7.2||h>18.2){top=[57,75,122];horizon=[214,144,103];fog=[161,166,177];light=[188,180,178]}else{top=[109,181,232];horizon=[222,241,249];fog=[205,219,227];light=[220,235,244]}const stormTop=[42,47,59],stormHor=[80,84,93],stormFog=[116,121,128],stormLight=[165,171,181];return{top:rgb(top,stormTop,storm),horizon:rgb(horizon,stormHor,storm),fog:rgb(fog,stormFog,storm),light:rgb(light,stormLight,storm)}}
function rememberPaint(){if(!map)return;try{if(map.getLayer('bp97-building')&&originals.buildingColor===null){originals.buildingColor=map.getPaintProperty('bp97-building','fill-extrusion-color');originals.buildingOpacity=map.getPaintProperty('bp97-building','fill-extrusion-opacity')}}catch(_){}try{if(map.getLayer('sat')&&originals.satBrightnessMax===null)originals.satBrightnessMax=map.getPaintProperty('sat','raster-brightness-max')}catch(_){}try{if(map.getLayer('street')&&originals.streetBrightnessMax===null)originals.streetBrightnessMax=map.getPaintProperty('street','raster-brightness-max')}catch(_){}}
function applyRenderer(){if(!map)return;rememberPaint();const vis=clamp(Number(state.visibilityMiles)||0,.05,30),cloud=clamp(state.cloudCoveragePct/100,0,1),storm=clamp(state.stormIntensity,0,1),heavy=vis<1,p=skyPalette();state.effectiveDrawDistanceMiles=effectiveDraw(vis);try{map.setProjection({type:'globe'});map.setRenderWorldCopies(false)}catch(_){}
 const density=clamp((5-vis)/5,0,1),groundBlend=heavy?clamp(.08+vis*.12,.08,.2):clamp(.34+density*.22,.34,.68);try{map.setSky({'sky-color':p.top,'sky-horizon-blend':clamp(.38+cloud*.25,0,1),'horizon-color':p.horizon,'horizon-fog-blend':clamp(.34+density*.55,0,1),'fog-color':p.fog,'fog-ground-blend':groundBlend,'atmosphere-blend':['interpolate',['linear'],['zoom'],0,1,5,1,7,0]})}catch(e){console.warn('BP2200 sky',e)}
 const h=localHour(),sun=(h-6)/12*Math.PI,az=((h/24)*360+180)%360,alt=Math.max(6,Math.sin(sun)*78),baseLight=(h<6||h>20)?.24:.52,intensity=clamp(baseLight*(1-storm*.62)*(1-cloud*.18),.1,.58);try{map.setLight({anchor:'map',color:p.light,intensity,position:[1.35,az,alt]})}catch(_){}
 const dim=clamp(1-storm*.42-cloud*.08-(heavy?.08:0),.48,1);for(const id of ['sat','street'])try{if(map.getLayer(id)){map.setPaintProperty(id,'raster-brightness-max',dim);map.setPaintProperty(id,'raster-saturation',storm?-.28*storm:0)}}catch(_){}
 for(const id of ['bp97-building','bp2174-context-buildings','bp2180-opp-building-glow'])try{if(map.getLayer(id))map.setPaintProperty(id,'fill-extrusion-opacity',clamp(.9-storm*.16-density*.12,.56,.92))}catch(_){}
 document.documentElement.style.setProperty('--bp2200-fog-density',String(density));document.documentElement.style.setProperty('--bp2200-storm-intensity',String(storm));document.documentElement.style.setProperty('--bp2200-draw-distance-mi',String(state.effectiveDrawDistanceMiles));
 window.dispatchEvent(new CustomEvent('bridgepoint:draw-distance',{detail:{miles:state.effectiveDrawDistanceMiles,visibilityMiles:vis,heavyFog:heavy}}));
 if(cloudGL)renderClouds(performance.now())
}
function applyState(next,explicit=true){if(!next||typeof next!=='object')return getState();const vis=Number(next.visibilityMiles??next.visibility_miles),cloud=Number(next.cloudCoveragePct??next.cloud_coverage_pct),storm=next.stormActive??next.storm_active,intensity=Number(next.stormIntensity??next.storm_intensity),alt=Number(next.cloudAltitudeM??next.cloud_altitude_m),tod=next.timeOfDay??next.time_of_day;if(Number.isFinite(vis))state.visibilityMiles=clamp(vis,.05,100);if(Number.isFinite(cloud))state.cloudCoveragePct=clamp(cloud,0,100);if(typeof storm==='boolean')state.stormActive=storm;if(Number.isFinite(intensity))state.stormIntensity=clamp(intensity,0,1);else if(typeof storm==='boolean')state.stormIntensity=storm?Math.max(.45,state.stormIntensity):0;if(Number.isFinite(alt))state.cloudAltitudeM=clamp(alt,300,18000);if(tod!==undefined)state.timeOfDay=tod;state.source=String(next.source||state.source||'EXTERNAL');state.lastUpdated=new Date().toISOString();if(explicit)explicitUntil=Date.now()+120000;applyRenderer();return getState()}
function getState(){return{...state,globe:map?.getProjection?.().type==='globe',cloudShader:!!cloudProgram}}
function makeCloudCanvas(){if(cloudCanvas)return;const shell=document.querySelector('.map-shell');if(!shell)return;const style=document.createElement('style');style.id='bp2200AtmosphereStyle';style.textContent='#bp2200CloudDeck{position:absolute;inset:0;z-index:8;pointer-events:none;mix-blend-mode:screen;opacity:1}';document.head.appendChild(style);cloudCanvas=document.createElement('canvas');cloudCanvas.id='bp2200CloudDeck';shell.appendChild(cloudCanvas);cloudGL=cloudCanvas.getContext('webgl2',{alpha:true,premultipliedAlpha:true})||cloudCanvas.getContext('webgl',{alpha:true,premultipliedAlpha:true});resizeClouds();if(cloudGL)initCloudGL();window.addEventListener('resize',resizeClouds,{passive:true})}
function resizeClouds(){if(!cloudCanvas)return;const b=cloudCanvas.parentElement.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,LOW?1:MOBILE?1.15:1.5);cloudCanvas.width=Math.max(2,Math.round(b.width*d));cloudCanvas.height=Math.max(2,Math.round(b.height*d));cloudCanvas.style.width=b.width+'px';cloudCanvas.style.height=b.height+'px';cloudGL?.viewport(0,0,cloudCanvas.width,cloudCanvas.height)}
function compile(type,src){const sh=cloudGL.createShader(type);cloudGL.shaderSource(sh,src);cloudGL.compileShader(sh);if(!cloudGL.getShaderParameter(sh,cloudGL.COMPILE_STATUS))throw Error(cloudGL.getShaderInfoLog(sh)||'cloud shader compile');return sh}
function initCloudGL(){try{const vs='attribute vec2 a;varying vec2 v;void main(){v=a*.5+.5;gl_Position=vec4(a,0.,1.);}';const fs=`precision mediump float;varying vec2 v;uniform float u_time;uniform float u_cover;uniform float u_storm;uniform float u_alt;uniform vec2 u_res;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){float s=0.,a=.5;for(int i=0;i<5;i++){s+=a*noise(p);p=p*2.03+vec2(17.1,9.2);a*=.5;}return s;}void main(){float aspect=u_res.x/max(1.,u_res.y);vec2 p=vec2(v.x*aspect,v.y);float parallax=clamp((8000.-u_alt)/8000.,.05,.95);p+=vec2(u_time*.008*(.35+parallax),u_time*.002);float n=fbm(p*3.6)+.38*fbm(p*8.3+7.2);float threshold=mix(1.15,.42,u_cover);float c=smoothstep(threshold,threshold+.28,n);float vertical=smoothstep(.03,.18,v.y)*(1.-smoothstep(.55,.88,v.y));c*=vertical;vec3 fair=vec3(.88,.93,.96),storm=vec3(.19,.21,.25),col=mix(fair,storm,u_storm);float alpha=c*mix(.15,.5,u_storm+.35*u_cover);gl_FragColor=vec4(col*alpha,alpha);}`;const p=cloudGL.createProgram();cloudGL.attachShader(p,compile(cloudGL.VERTEX_SHADER,vs));cloudGL.attachShader(p,compile(cloudGL.FRAGMENT_SHADER,fs));cloudGL.linkProgram(p);if(!cloudGL.getProgramParameter(p,cloudGL.LINK_STATUS))throw Error(cloudGL.getProgramInfoLog(p)||'cloud program link');cloudProgram=p;const b=cloudGL.createBuffer();cloudGL.bindBuffer(cloudGL.ARRAY_BUFFER,b);cloudGL.bufferData(cloudGL.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),cloudGL.STATIC_DRAW);const a=cloudGL.getAttribLocation(p,'a');cloudGL.enableVertexAttribArray(a);cloudGL.vertexAttribPointer(a,2,cloudGL.FLOAT,false,0,0);cloudGL.enable(cloudGL.BLEND);cloudGL.blendFunc(cloudGL.ONE,cloudGL.ONE_MINUS_SRC_ALPHA);startClouds()}catch(e){console.warn('BP2200 cloud GPU',e);cloudProgram=null}}
function renderClouds(t){if(!cloudGL||!cloudProgram)return;const cover=clamp(state.cloudCoveragePct/100,0,1),storm=clamp(state.stormIntensity,0,1);cloudGL.clearColor(0,0,0,0);cloudGL.clear(cloudGL.COLOR_BUFFER_BIT);if(cover<.02&&!state.stormActive)return;cloudGL.useProgram(cloudProgram);cloudGL.uniform1f(cloudGL.getUniformLocation(cloudProgram,'u_time'),t/1000);cloudGL.uniform1f(cloudGL.getUniformLocation(cloudProgram,'u_cover'),cover);cloudGL.uniform1f(cloudGL.getUniformLocation(cloudProgram,'u_storm'),storm);cloudGL.uniform1f(cloudGL.getUniformLocation(cloudProgram,'u_alt'),state.cloudAltitudeM);cloudGL.uniform2f(cloudGL.getUniformLocation(cloudProgram,'u_res'),cloudCanvas.width,cloudCanvas.height);cloudGL.drawArrays(cloudGL.TRIANGLES,0,6)}
function startClouds(){cancelAnimationFrame(cloudRAF);const loop=t=>{cloudRAF=requestAnimationFrame(loop);if(document.hidden||t-lastCloudFrame<(LOW?80:MOBILE?50:33))return;lastCloudFrame=t;renderClouds(t)};cloudRAF=requestAnimationFrame(loop)}
function install(){S=window.__bp97MapState;map=S?.map;if(!S?.ready||!map){setTimeout(install,180);return}makeCloudCanvas();try{map.setProjection({type:'globe'});map.setRenderWorldCopies(false)}catch(_){}map.on('moveend',()=>{autoState();applyRenderer()});map.on('zoomend',applyRenderer);pollTimer=setInterval(autoState,5000);autoState();applyRenderer();console.info('BridgePoint Atmosphere V2200 ready')}
window.BridgePointAtmosphereV2200={version:VERSION,setWeather:v=>applyState(v,true),setVisibilityMiles:v=>applyState({visibilityMiles:v,source:'EXTERNAL_VISIBILITY'},true),setCloudCoveragePct:v=>applyState({cloudCoveragePct:v,source:'EXTERNAL_CLOUDS'},true),setStorm:(active,intensity)=>applyState({stormActive:!!active,stormIntensity:Number.isFinite(+intensity)?+intensity:(active?.65:0),source:'EXTERNAL_STORM'},true),setCloudAltitudeM:v=>applyState({cloudAltitudeM:v,source:'EXTERNAL_ALTITUDE'},true),getState,refresh:autoState};
window.addEventListener('bridgepoint:atmosphere',e=>applyState(e.detail||{},true));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();