(()=>{
'use strict';
if(window.__bridgepointPrecipitationV2201)return;window.__bridgepointPrecipitationV2201=true;
const VERSION=2201,$=q=>document.querySelector(q),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rad=d=>d*Math.PI/180;
const MOBILE=innerWidth<=760||/Android|iPhone|iPad/i.test(navigator.userAgent),LOW=Number(navigator.deviceMemory||4)<=3||Number(navigator.hardwareConcurrency||4)<=4;
let S=null,map=null,canvas=null,gl=null,program=null,buffer=null,raf=0,last=0,explicitUntil=0;
const CAP=LOW?700:MOBILE?1450:2600,STRIDE=5,data=new Float32Array(CAP*STRIDE);
let state={enabled:true,type:'none',intensity:.55,windSpeedMph:0,windDirectionDeg:0,source:'AUTO',groundElevationM:0,lastUpdated:null};
function compile(type,src){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh)||'shader compile');return sh}
function initGL(){if(!gl)return;try{const vs=`attribute vec2 a_seed;attribute float a_speed;attribute float a_size;attribute float a_phase;uniform float u_time;uniform float u_kind;uniform vec2 u_wind;uniform float u_ground;varying float v_kind;varying vec2 v_vel;varying float v_phase;float h(float x){return fract(sin(x*91.731)*43758.5453);}void main(){float t=u_time;float k=u_kind;vec2 p=a_seed;vec2 vel=normalize(vec2(u_wind.x*.72,1.0+u_wind.y*.20));if(k<.5){float y=fract(a_seed.y+t*a_speed*.46);float x=fract(a_seed.x+t*u_wind.x*(.025+.025*a_speed));p=vec2(x,y*1.18-.09);gl_PointSize=a_size+min(18.0,length(u_wind)*10.0);}else if(k<1.5){float y=fract(a_seed.y+t*a_speed*.095);float drift=sin(t*(1.2+a_phase*.7)+a_phase*12.0)*(.015+.02*a_phase);float x=fract(a_seed.x+drift+t*u_wind.x*.008);p=vec2(x,y*1.12-.06);gl_PointSize=a_size;}else{float y=fract(a_seed.y+t*a_speed*.72);float gy=max(.62,u_ground);float yy=y*1.12-.05;float hit=smoothstep(gy-.035,gy+.015,yy);float bounce=hit*sin(clamp((yy-gy)/.11,0.0,1.0)*3.14159)*.035;yy=min(yy,gy+.09)-bounce;float x=fract(a_seed.x+t*u_wind.x*.005);p=vec2(x,yy);gl_PointSize=a_size;}gl_Position=vec4(p.x*2.0-1.0,1.0-p.y*2.0,0.,1.);v_kind=k;v_vel=vel;v_phase=a_phase;}`;
const fs=`precision mediump float;varying float v_kind;varying vec2 v_vel;varying float v_phase;void main(){vec2 q=gl_PointCoord-vec2(.5);float a=0.;vec3 c=vec3(1.);if(v_kind<.5){float ang=atan(v_vel.x,v_vel.y);float cs=cos(ang),sn=sin(ang);vec2 r=vec2(cs*q.x-sn*q.y,sn*q.x+cs*q.y);float core=1.0-smoothstep(.035,.105,abs(r.x));float longf=1.0-smoothstep(.18,.5,abs(r.y));a=core*longf*.62;c=vec3(.48,.67,.76);}else if(v_kind<1.5){float d=length(q);a=(1.0-smoothstep(.28,.49,d))*(.62+.23*sin(v_phase*19.));c=vec3(.97,.985,1.);}else{float d=length(q);a=(1.0-smoothstep(.25,.49,d))*.86;c=vec3(.82,.93,1.);}if(a<.01)discard;gl_FragColor=vec4(c,a);}`;
program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vs));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)||'program link');buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(let i=0;i<CAP;i++){const o=i*STRIDE,dataSeed=(i*16807)%2147483647;data[o]=(dataSeed%997)/997;data[o+1]=((dataSeed*13)%991)/991;data[o+2]=.55+((dataSeed%101)/101)*.85;data[o+3]=2.4+((dataSeed%23)/23)*5.5;data[o+4]=((dataSeed%89)/89)}gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.useProgram(program);const stride=STRIDE*4;[['a_seed',2,0],['a_speed',1,2],['a_size',1,3],['a_phase',1,4]].forEach(([n,s,o])=>{const l=gl.getAttribLocation(program,n);gl.enableVertexAttribArray(l);gl.vertexAttribPointer(l,s,gl.FLOAT,false,stride,o*4)});gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.disable(gl.DEPTH_TEST)}catch(e){console.warn('BP2201 GL init',e);program=null}}
function makeCanvas(){if(canvas)return;const shell=$('.map-shell');if(!shell)return;canvas=document.createElement('canvas');canvas.id='bp2201Precipitation';canvas.style.cssText='position:absolute;inset:0;z-index:12;pointer-events:none';shell.appendChild(canvas);gl=canvas.getContext('webgl2',{alpha:true,antialias:false,premultipliedAlpha:true})||canvas.getContext('webgl',{alpha:true,antialias:false,premultipliedAlpha:true});resize();initGL();window.addEventListener('resize',resize,{passive:true})}
function resize(){if(!canvas)return;const b=canvas.parentElement.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,LOW?1:MOBILE?1.25:1.5);canvas.width=Math.max(2,Math.round(b.width*d));canvas.height=Math.max(2,Math.round(b.height*d));canvas.style.width=b.width+'px';canvas.style.height=b.height+'px';gl?.viewport(0,0,canvas.width,canvas.height)}
function nearestObs(){const a=window.BridgePointWorldEffects?.getState?.()?.data?.observations;if(!Array.isArray(a)||!a.length||!map)return null;const c=map.getCenter();let best=null,bd=Infinity;for(const o of a){const lng=+o.lng,lat=+o.lat;if(!Number.isFinite(lng)||!Number.isFinite(lat))continue;const dx=(lng-c.lng)*Math.cos(rad(c.lat)),dy=lat-c.lat,d=dx*dx+dy*dy;if(d<bd){bd=d;best=o}}return best}
function inferType(o){const s=String([o?.weather,o?.weather_text,o?.present_weather,o?.wx,o?.condition,o?.conditions].filter(Boolean).join(' ')).toLowerCase();if(/hail|ice pellets|graupel/.test(s))return'hail';if(/snow|flurr|blizzard/.test(s))return'snow';if(/rain|drizzle|shower|thunder/.test(s))return'rain';const fx=window.BridgePointWorldEffects?.getState?.();const mode=String(fx?.mode||'').toLowerCase();if(['rain','snow','hail'].includes(mode))return mode;return'none'}
function autoState(){if(Date.now()<explicitUntil)return;const o=nearestObs();if(!o)return;const ws=Number(o.wind_speed_mph??(Number.isFinite(+o.wind_speed_kt)?+o.wind_speed_kt*1.15078:NaN)),wd=Number(o.wind_dir_deg),type=inferType(o);setState({type,windSpeedMph:Number.isFinite(ws)?ws:state.windSpeedMph,windDirectionDeg:Number.isFinite(wd)?wd:state.windDirectionDeg,source:'LIVE_OBSERVATION'},false)}
function setState(v,explicit=true){if(!v||typeof v!=='object')return getState();const type=String(v.type??v.precipitationType??v.precipitation_type??state.type).toLowerCase();if(['none','rain','snow','hail'].includes(type))state.type=type;const ws=Number(v.windSpeedMph??v.wind_speed_mph),wd=Number(v.windDirectionDeg??v.wind_direction_deg),int=Number(v.intensity);if(Number.isFinite(ws))state.windSpeedMph=clamp(ws,0,220);if(Number.isFinite(wd))state.windDirectionDeg=((wd%360)+360)%360;if(Number.isFinite(int))state.intensity=clamp(int,0,1);if(typeof v.enabled==='boolean')state.enabled=v.enabled;state.source=String(v.source||state.source);state.lastUpdated=new Date().toISOString();if(explicit)explicitUntil=Date.now()+120000;start();return getState()}
function windVector(){const toward=(state.windDirectionDeg+180-(map?.getBearing?.()||0))%360,a=rad(toward),strength=clamp(state.windSpeedMph/70,0,2.2);return{x:Math.sin(a)*strength,y:-Math.cos(a)*strength}}
function groundBand(){const pitch=Number(map?.getPitch?.()||0);let elev=0;try{elev=Number(map.queryTerrainElevation?.(map.getCenter())||0)}catch(_){}state.groundElevationM=elev;return clamp(.94-pitch/520-elev/20000,.72,.95)}
function kind(){return state.type==='rain'?0:state.type==='snow'?1:state.type==='hail'?2:-1}
function frame(t){raf=requestAnimationFrame(frame);if(document.hidden||!state.enabled||!program||state.type==='none'){if(gl){gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT)}return}if(t-last<(LOW?42:MOBILE?27:16))return;last=t;const k=kind(),w=windVector(),base=k===0?(LOW?420:MOBILE?900:1600):k===1?(LOW?320:MOBILE?720:1250):(LOW?260:MOBILE?620:1000),count=Math.max(20,Math.floor(base*clamp(state.intensity,.08,1)));gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(program);gl.uniform1f(gl.getUniformLocation(program,'u_time'),t/1000);gl.uniform1f(gl.getUniformLocation(program,'u_kind'),k);gl.uniform2f(gl.getUniformLocation(program,'u_wind'),w.x,w.y);gl.uniform1f(gl.getUniformLocation(program,'u_ground'),groundBand());gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.drawArrays(gl.POINTS,0,Math.min(count,CAP))}
function start(){if(!raf)raf=requestAnimationFrame(frame)}
function stop(){cancelAnimationFrame(raf);raf=0;if(gl){gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT)}}
function install(){S=window.__bp97MapState;map=S?.map;if(!S?.ready||!map){setTimeout(install,180);return}makeCanvas();map.on('moveend',()=>{resize();autoState()});map.on('zoomend',resize);setInterval(autoState,5000);autoState();start();console.info('BridgePoint Precipitation V2201 ready')}
window.BridgePointPrecipitationV2201={version:VERSION,setPrecipitation:v=>setState(v,true),setType:type=>setState({type,source:'EXTERNAL_TYPE'},true),setWind:(speedMph,directionDeg)=>setState({windSpeedMph:speedMph,windDirectionDeg:directionDeg,source:'EXTERNAL_WIND'},true),enable:()=>setState({enabled:true},true),disable:()=>{setState({enabled:false},true);stop()},getState};
function getState(){return{...state,gpu:!!program,cameraLocal:true}}
window.addEventListener('bridgepoint:precipitation',e=>setState(e.detail||{},true));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();