(function(){
const SUPA='https://xdfsjztwgsbmabshzsjw.supabase.co';
const KEY='sb_publishable_lM9oWQeHjBmgOIiteeOicQ_PTyAeF25';
const H={'apikey':KEY,'Content-Type':'application/json','Accept':'application/json'};
async function rpc(n,a){const r=await fetch(SUPA+'/rest/v1/rpc/'+n,{method:'POST',headers:H,body:JSON.stringify(a||{}),cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d?.message||('HTTP '+r.status));return d}
async function resolve(el){let id=(el.dataset.propertyId||'').trim(),address=(el.dataset.address||'').trim();if(!id&&address){const s=await rpc('bridgepoint_public_search_v5200',{p_query:address,p_limit:2});id=s?.results?.find(x=>x.property_id)?.property_id||''}if(!id)throw new Error('PROPERTY NOT RESOLVED');return id}
function style(){if(document.getElementById('bp-bii-embed-css'))return;const s=document.createElement('style');s.id='bp-bii-embed-css';s.textContent='.bp-bii-badge{display:inline-flex;align-items:center;gap:9px;padding:8px 10px;border:1px solid #28546b;border-radius:9px;background:#061019;color:#eaf9ff;font:700 12px/1.2 system-ui,-apple-system,sans-serif;text-decoration:none}.bp-bii-badge b{font-size:15px}.bp-bii-badge small{display:block;color:#8aa7b5;font-size:9px;margin-top:2px}.bp-bii-badge i{width:8px;height:8px;border-radius:50%;background:#ffd26a;box-shadow:0 0 9px rgba(255,210,106,.5)}.bp-bii-badge[data-state="published"] i{background:#70e6a7;box-shadow:0 0 9px rgba(112,230,167,.5)}';document.head.appendChild(s)}
async function mount(el){style();el.innerHTML='<a class="bp-bii-badge" href="https://bridgepointintelligence.online/integrity-index/" target="_blank" rel="noopener"><i></i><span><b>BII …</b><small>BridgePoint Integrity Index</small></span></a>';const a=el.querySelector('a'),b=el.querySelector('b'),sm=el.querySelector('small');try{const id=await resolve(el),d=await rpc('bridgepoint_public_integrity_index_v5200',{p_property_id:id});if(d.index_value==null){b.textContent='BII · WITHHELD';sm.textContent=(d.publication_status||'INSUFFICIENT_DATA').replaceAll('_',' ')+' · confidence '+Number(d.confidence||0).toFixed(2)}else{a.dataset.state='published';b.textContent='BII '+Number(d.index_value).toFixed(1)+'/100';sm.textContent='confidence '+Number(d.confidence||0).toFixed(2)+' · '+(d.health_band||'')}}catch(e){b.textContent='BII · UNAVAILABLE';sm.textContent=String(e.message||e)}}
document.querySelectorAll('.bridgepoint-bii').forEach(mount);
})();