const SUPA='https://xdfsjztwgsbmabshzsjw.supabase.co',KEY='sb_publishable_lM9oWQeHjBmgOIiteeOicQ_PTyAeF25',H={'apikey':KEY,'Content-Type':'application/json','Accept':'application/json'};const $=x=>document.getElementById(x);
async function rpc(n,a){const r=await fetch(SUPA+'/rest/v1/rpc/'+n,{method:'POST',headers:H,body:JSON.stringify(a||{})}),d=await r.json();if(!r.ok)throw new Error(d?.message||('HTTP '+r.status));return d}
async function lookup(q){const s=await rpc('bridgepoint_public_search_v5200',{p_query:q,p_limit:4}),row=(s.results||[]).find(x=>x.property_id);if(!row)throw new Error('No BridgePoint property match');const d=await rpc('bridgepoint_public_integrity_index_v5200',{p_property_id:row.property_id});return{row,d}}
function render(q,row,d){const out=$('r'),label=d.index_value==null?'BII · WITHHELD':'BII '+Number(d.index_value).toFixed(1)+'/100',status=String(d.publication_status||'').replaceAll('_',' '),confidence=Number(d.confidence||0).toFixed(3),address=row.full_address||q,lat=Number(row.latitude),lng=Number(row.longitude),deep=(Number.isFinite(lat)&&Number.isFinite(lng)?'https://bridgepointintelligence.online/app/?lat='+encodeURIComponent(lat)+'&lng='+encodeURIComponent(lng)+'&z=18&select=1':'https://bridgepointintelligence.online/app/?address='+encodeURIComponent(address))+'&utm_source=bii_extension&utm_medium=browser_extension&utm_campaign=distribution';out.hidden=false;out.innerHTML='<b>'+label+'</b><div>'+status+'</div><div class="small">Confidence '+confidence+' · components '+Number(d.observed_component_count||0)+'</div><div class="small">'+address+'</div><div style="margin-top:8px;display:flex;gap:10px;flex-wrap:wrap"><a target="_blank" href="'+deep+'">Open full property</a><a target="_blank" href="https://bridgepointintelligence.online/integrity-index/?utm_source=bii_extension&utm_medium=browser_extension&utm_campaign=distribution">Methodology</a></div>';chrome.storage.local.set({last:q});return{label,status,confidence,address,url:deep}}
async function manual(q){const out=$('r');out.hidden=false;out.textContent='Resolving…';const {row,d}=await lookup(q);return render(q,row,d)}
$('go').onclick=async()=>{const q=$('q').value.trim();if(q.length<4){$('r').hidden=false;$('r').textContent='Enter an exact address.';return}try{await manual(q)}catch(e){$('r').textContent=String(e.message||e)}};
function extractAddressFromPage(){
 const clean=s=>String(s||'').replace(/\s+/g,' ').trim(),join=a=>a.filter(Boolean).map(clean).filter(Boolean).join(', '),c=[];
 document.querySelectorAll('script[type="application/ld+json"]').forEach(s=>{try{const v=JSON.parse(s.textContent||'null');const walk=x=>{if(!x)return;if(Array.isArray(x)){x.forEach(walk);return}if(typeof x!=='object')return;if(x.address){let z='';if(typeof x.address==='string')z=clean(x.address);else z=join([x.address.streetAddress,x.address.addressLocality,x.address.addressRegion,x.address.postalCode]);if(z)c.push(z)}for(const k of ['@graph','mainEntity','itemListElement','about'])if(x[k])walk(x[k])};walk(v)}catch(_){}});
 const item=join([document.querySelector('[itemprop="streetAddress"]')?.textContent,document.querySelector('[itemprop="addressLocality"]')?.textContent,document.querySelector('[itemprop="addressRegion"]')?.textContent,document.querySelector('[itemprop="postalCode"]')?.textContent]);if(item)c.push(item);
 const meta=[document.querySelector('meta[property="og:title"]')?.content,document.querySelector('meta[name="twitter:title"]')?.content,document.title].filter(Boolean).map(clean);
 const re=/\b\d{1,7}\s+[A-Za-z0-9.'# -]{2,60}\s(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Drive|Dr|Lane|Ln|Court|Ct|Circle|Cir|Way|Place|Pl|Parkway|Pkwy|Highway|Hwy|Terrace|Ter)\b[^|·]{0,60}/i;for(const m of meta){const z=m.match(re)?.[0];if(z)c.push(clean(z))}return{address:c[0]||''}
}
function showOverlay(data){let el=document.getElementById('bridgepoint-bii-user-overlay');if(!el){el=document.createElement('a');el.id='bridgepoint-bii-user-overlay';el.target='_blank';el.rel='noopener';document.documentElement.appendChild(el)}el.href=data.url;el.textContent='';Object.assign(el.style,{position:'fixed',right:'16px',bottom:'16px',zIndex:'2147483647',display:'block',maxWidth:'310px',padding:'12px 14px',borderRadius:'12px',border:'1px solid #2c627b',background:'#061019',color:'#effaff',boxShadow:'0 12px 40px rgba(0,0,0,.42)',font:'700 13px/1.35 system-ui,-apple-system,sans-serif',textDecoration:'none'});const a=document.createElement('div');a.textContent=data.label;a.style.fontSize='16px';a.style.fontWeight='900';const b=document.createElement('div');b.textContent=data.status+' · confidence '+data.confidence;b.style.color='#8aa6b5';b.style.fontSize='10px';const c=document.createElement('div');c.textContent=data.address;c.style.fontSize='11px';c.style.marginTop='6px';const d=document.createElement('div');d.textContent='BridgePoint BII · user-installed overlay';d.style.color='#62e7ff';d.style.fontSize='9px';d.style.marginTop='6px';el.append(a,b,c,d)}
$('analyze').onclick=async()=>{const out=$('r');out.hidden=false;out.textContent='Reading current-tab address metadata…';try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id)throw new Error('No active tab');const x=await chrome.scripting.executeScript({target:{tabId:tab.id},func:extractAddressFromPage});const q=x?.[0]?.result?.address||'';if(!q)throw new Error('No address metadata found. Enter the address manually.');$('q').value=q;const overlay=await manual(q);await chrome.scripting.executeScript({target:{tabId:tab.id},func:showOverlay,args:[overlay]})}catch(e){out.textContent=String(e.message||e)}};
chrome.storage.local.get(['last'],x=>{if(x.last)$('q').value=x.last});